//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT.TS360API.ExternalServices.BTStockCheckServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://edi.btol.com/", ConfigurationName="BTStockCheckServices.StockCheckSoap")]
    public interface StockCheckSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://edi.btol.com/StockCheckByParameters", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BT.TS360API.ExternalServices.BTStockCheckServices.StockCheckResponse StockCheckByParameters(string SystemID, string SystemPassword, string AccountID, string ItemID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://edi.btol.com/StockCheckByParameters", ReplyAction="*")]
        System.Threading.Tasks.Task<BT.TS360API.ExternalServices.BTStockCheckServices.StockCheckResponse> StockCheckByParametersAsync(string SystemID, string SystemPassword, string AccountID, string ItemID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://edi.btol.com/StockCheckByClass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BT.TS360API.ExternalServices.BTStockCheckServices.StockCheckResponse StockCheckByClass(BT.TS360API.ExternalServices.BTStockCheckServices.StockCheckRequest RequestClass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://edi.btol.com/StockCheckByClass", ReplyAction="*")]
        System.Threading.Tasks.Task<BT.TS360API.ExternalServices.BTStockCheckServices.StockCheckResponse> StockCheckByClassAsync(BT.TS360API.ExternalServices.BTStockCheckServices.StockCheckRequest RequestClass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://edi.btol.com/StockCheckByCart", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BT.TS360API.ExternalServices.BTStockCheckServices.CartStockCheckResponse StockCheckByCart(BT.TS360API.ExternalServices.BTStockCheckServices.CartStockCheckRequest MultilineRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://edi.btol.com/StockCheckByCart", ReplyAction="*")]
        System.Threading.Tasks.Task<BT.TS360API.ExternalServices.BTStockCheckServices.CartStockCheckResponse> StockCheckByCartAsync(BT.TS360API.ExternalServices.BTStockCheckServices.CartStockCheckRequest MultilineRequest);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edi.btol.com/")]
    public partial class StockCheckResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusMessageField;
        
        private string accountIDField;
        
        private string accountIDTypeField;
        
        private string itemIDField;
        
        private string itemIDTypeField;
        
        private string replacementItemIDField;
        
        private WHS[] warehousesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StatusMessage {
            get {
                return this.statusMessageField;
            }
            set {
                this.statusMessageField = value;
                this.RaisePropertyChanged("StatusMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AccountID {
            get {
                return this.accountIDField;
            }
            set {
                this.accountIDField = value;
                this.RaisePropertyChanged("AccountID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AccountIDType {
            get {
                return this.accountIDTypeField;
            }
            set {
                this.accountIDTypeField = value;
                this.RaisePropertyChanged("AccountIDType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ItemID {
            get {
                return this.itemIDField;
            }
            set {
                this.itemIDField = value;
                this.RaisePropertyChanged("ItemID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ItemIDType {
            get {
                return this.itemIDTypeField;
            }
            set {
                this.itemIDTypeField = value;
                this.RaisePropertyChanged("ItemIDType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ReplacementItemID {
            get {
                return this.replacementItemIDField;
            }
            set {
                this.replacementItemIDField = value;
                this.RaisePropertyChanged("ReplacementItemID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Warehouse")]
        public WHS[] Warehouses {
            get {
                return this.warehousesField;
            }
            set {
                this.warehousesField = value;
                this.RaisePropertyChanged("Warehouses");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edi.btol.com/")]
    public partial class WHS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string wHSCodeField;
        
        private string wHSDescriptionField;
        
        private int qTYOnHandField;
        
        private int qTYOnOrderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string WHSCode {
            get {
                return this.wHSCodeField;
            }
            set {
                this.wHSCodeField = value;
                this.RaisePropertyChanged("WHSCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string WHSDescription {
            get {
                return this.wHSDescriptionField;
            }
            set {
                this.wHSDescriptionField = value;
                this.RaisePropertyChanged("WHSDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int QTYOnHand {
            get {
                return this.qTYOnHandField;
            }
            set {
                this.qTYOnHandField = value;
                this.RaisePropertyChanged("QTYOnHand");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int QTYOnOrder {
            get {
                return this.qTYOnOrderField;
            }
            set {
                this.qTYOnOrderField = value;
                this.RaisePropertyChanged("QTYOnOrder");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edi.btol.com/")]
    public partial class WHSOHOnly : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string wHSCodeField;
        
        private string wHSDescriptionField;
        
        private int qTYOnHandField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string WHSCode {
            get {
                return this.wHSCodeField;
            }
            set {
                this.wHSCodeField = value;
                this.RaisePropertyChanged("WHSCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string WHSDescription {
            get {
                return this.wHSDescriptionField;
            }
            set {
                this.wHSDescriptionField = value;
                this.RaisePropertyChanged("WHSDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int QTYOnHand {
            get {
                return this.qTYOnHandField;
            }
            set {
                this.qTYOnHandField = value;
                this.RaisePropertyChanged("QTYOnHand");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edi.btol.com/")]
    public partial class ResponseLineItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ProductIDTypes itemIDTypeField;
        
        private string itemIDField;
        
        private int orderQuantityField;
        
        private string eRPLineStatusCodeField;
        
        private string statusMessageField;
        
        private WHSOHOnly[] warehousehosesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ProductIDTypes ItemIDType {
            get {
                return this.itemIDTypeField;
            }
            set {
                this.itemIDTypeField = value;
                this.RaisePropertyChanged("ItemIDType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ItemID {
            get {
                return this.itemIDField;
            }
            set {
                this.itemIDField = value;
                this.RaisePropertyChanged("ItemID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int OrderQuantity {
            get {
                return this.orderQuantityField;
            }
            set {
                this.orderQuantityField = value;
                this.RaisePropertyChanged("OrderQuantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ERPLineStatusCode {
            get {
                return this.eRPLineStatusCodeField;
            }
            set {
                this.eRPLineStatusCodeField = value;
                this.RaisePropertyChanged("ERPLineStatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string StatusMessage {
            get {
                return this.statusMessageField;
            }
            set {
                this.statusMessageField = value;
                this.RaisePropertyChanged("StatusMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Warehouse")]
        public WHSOHOnly[] Warehousehoses {
            get {
                return this.warehousehosesField;
            }
            set {
                this.warehousehosesField = value;
                this.RaisePropertyChanged("Warehousehoses");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edi.btol.com/")]
    public enum ProductIDTypes {
        
        /// <remarks/>
        ISBN,
        
        /// <remarks/>
        BTKey,
        
        /// <remarks/>
        UPC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edi.btol.com/")]
    public partial class CartStockCheckResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusMessageField;
        
        private string eRPResponseStatusCodeField;
        
        private AccountTypes accountIDTypeField;
        
        private string accountIDField;
        
        private int totalOrderQuantityField;
        
        private ResponseLineItem[] lineItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StatusMessage {
            get {
                return this.statusMessageField;
            }
            set {
                this.statusMessageField = value;
                this.RaisePropertyChanged("StatusMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ERPResponseStatusCode {
            get {
                return this.eRPResponseStatusCodeField;
            }
            set {
                this.eRPResponseStatusCodeField = value;
                this.RaisePropertyChanged("ERPResponseStatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public AccountTypes AccountIDType {
            get {
                return this.accountIDTypeField;
            }
            set {
                this.accountIDTypeField = value;
                this.RaisePropertyChanged("AccountIDType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string AccountID {
            get {
                return this.accountIDField;
            }
            set {
                this.accountIDField = value;
                this.RaisePropertyChanged("AccountID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int TotalOrderQuantity {
            get {
                return this.totalOrderQuantityField;
            }
            set {
                this.totalOrderQuantityField = value;
                this.RaisePropertyChanged("TotalOrderQuantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("LineItem")]
        public ResponseLineItem[] LineItems {
            get {
                return this.lineItemsField;
            }
            set {
                this.lineItemsField = value;
                this.RaisePropertyChanged("LineItems");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edi.btol.com/")]
    public enum AccountTypes {
        
        /// <remarks/>
        AccountNumber,
        
        /// <remarks/>
        SAN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edi.btol.com/")]
    public partial class LineItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ProductIDTypes itemIDTypeField;
        
        private string itemIDField;
        
        private int orderQuantityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ProductIDTypes ItemIDType {
            get {
                return this.itemIDTypeField;
            }
            set {
                this.itemIDTypeField = value;
                this.RaisePropertyChanged("ItemIDType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ItemID {
            get {
                return this.itemIDField;
            }
            set {
                this.itemIDField = value;
                this.RaisePropertyChanged("ItemID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int OrderQuantity {
            get {
                return this.orderQuantityField;
            }
            set {
                this.orderQuantityField = value;
                this.RaisePropertyChanged("OrderQuantity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edi.btol.com/")]
    public partial class CartStockCheckRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string systemIDField;
        
        private string systemPasswordField;
        
        private AccountTypes accountIDTypeField;
        
        private string accountIDField;
        
        private string targetERPField;
        
        private int totalOrderQuantityField;
        
        private LineItem[] lineItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SystemID {
            get {
                return this.systemIDField;
            }
            set {
                this.systemIDField = value;
                this.RaisePropertyChanged("SystemID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SystemPassword {
            get {
                return this.systemPasswordField;
            }
            set {
                this.systemPasswordField = value;
                this.RaisePropertyChanged("SystemPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public AccountTypes AccountIDType {
            get {
                return this.accountIDTypeField;
            }
            set {
                this.accountIDTypeField = value;
                this.RaisePropertyChanged("AccountIDType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string AccountID {
            get {
                return this.accountIDField;
            }
            set {
                this.accountIDField = value;
                this.RaisePropertyChanged("AccountID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TargetERP {
            get {
                return this.targetERPField;
            }
            set {
                this.targetERPField = value;
                this.RaisePropertyChanged("TargetERP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int TotalOrderQuantity {
            get {
                return this.totalOrderQuantityField;
            }
            set {
                this.totalOrderQuantityField = value;
                this.RaisePropertyChanged("TotalOrderQuantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public LineItem[] LineItems {
            get {
                return this.lineItemsField;
            }
            set {
                this.lineItemsField = value;
                this.RaisePropertyChanged("LineItems");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edi.btol.com/")]
    public partial class StockCheckRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string systemIDField;
        
        private string systemPasswordField;
        
        private string accountIDField;
        
        private string itemIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SystemID {
            get {
                return this.systemIDField;
            }
            set {
                this.systemIDField = value;
                this.RaisePropertyChanged("SystemID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SystemPassword {
            get {
                return this.systemPasswordField;
            }
            set {
                this.systemPasswordField = value;
                this.RaisePropertyChanged("SystemPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AccountID {
            get {
                return this.accountIDField;
            }
            set {
                this.accountIDField = value;
                this.RaisePropertyChanged("AccountID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ItemID {
            get {
                return this.itemIDField;
            }
            set {
                this.itemIDField = value;
                this.RaisePropertyChanged("ItemID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StockCheckSoapChannel : BT.TS360API.ExternalServices.BTStockCheckServices.StockCheckSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StockCheckSoapClient : System.ServiceModel.ClientBase<BT.TS360API.ExternalServices.BTStockCheckServices.StockCheckSoap>, BT.TS360API.ExternalServices.BTStockCheckServices.StockCheckSoap {
        
        public StockCheckSoapClient() {
        }
        
        public StockCheckSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StockCheckSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockCheckSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockCheckSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BT.TS360API.ExternalServices.BTStockCheckServices.StockCheckResponse StockCheckByParameters(string SystemID, string SystemPassword, string AccountID, string ItemID) {
            return base.Channel.StockCheckByParameters(SystemID, SystemPassword, AccountID, ItemID);
        }
        
        public System.Threading.Tasks.Task<BT.TS360API.ExternalServices.BTStockCheckServices.StockCheckResponse> StockCheckByParametersAsync(string SystemID, string SystemPassword, string AccountID, string ItemID) {
            return base.Channel.StockCheckByParametersAsync(SystemID, SystemPassword, AccountID, ItemID);
        }
        
        public BT.TS360API.ExternalServices.BTStockCheckServices.StockCheckResponse StockCheckByClass(BT.TS360API.ExternalServices.BTStockCheckServices.StockCheckRequest RequestClass) {
            return base.Channel.StockCheckByClass(RequestClass);
        }
        
        public System.Threading.Tasks.Task<BT.TS360API.ExternalServices.BTStockCheckServices.StockCheckResponse> StockCheckByClassAsync(BT.TS360API.ExternalServices.BTStockCheckServices.StockCheckRequest RequestClass) {
            return base.Channel.StockCheckByClassAsync(RequestClass);
        }
        
        public BT.TS360API.ExternalServices.BTStockCheckServices.CartStockCheckResponse StockCheckByCart(BT.TS360API.ExternalServices.BTStockCheckServices.CartStockCheckRequest MultilineRequest) {
            return base.Channel.StockCheckByCart(MultilineRequest);
        }
        
        public System.Threading.Tasks.Task<BT.TS360API.ExternalServices.BTStockCheckServices.CartStockCheckResponse> StockCheckByCartAsync(BT.TS360API.ExternalServices.BTStockCheckServices.CartStockCheckRequest MultilineRequest) {
            return base.Channel.StockCheckByCartAsync(MultilineRequest);
        }
    }
}
