//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT.TS360API.ExternalServices.MARCProfilerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MARCProfilerService.IMARCProfiler")]
    public interface IMARCProfiler {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMARCProfiler/GetMARCFile", ReplyAction="http://tempuri.org/IMARCProfiler/GetMARCFileResponse")]
        string GetMARCFile(string sortColumn, string basketSummaryID, string sortDirection, string ProfileID, string FullIndicator, bool isOrdered, bool isCancelled, bool isOCLCEnabled, bool isBTEmployee, bool hasInventoryRules, string marketType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMARCProfiler/GetMARCFile", ReplyAction="http://tempuri.org/IMARCProfiler/GetMARCFileResponse")]
        System.Threading.Tasks.Task<string> GetMARCFileAsync(string sortColumn, string basketSummaryID, string sortDirection, string ProfileID, string FullIndicator, bool isOrdered, bool isCancelled, bool isOCLCEnabled, bool isBTEmployee, bool hasInventoryRules, string marketType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMARCProfiler/SendMARCFileFTP", ReplyAction="http://tempuri.org/IMARCProfiler/SendMARCFileFTPResponse")]
        void SendMARCFileFTP(
                    string sortColumn, 
                    string basketSummaryID, 
                    string sortDirection, 
                    string ProfileID, 
                    string FullIndicator, 
                    bool isOrdered, 
                    bool isCancelled, 
                    bool isOCLCEnabled, 
                    bool isBTEmployee, 
                    bool hasInventoryRules, 
                    string marketType, 
                    string FTPServer, 
                    string FTPUserID, 
                    string FTPPassword, 
                    string FTPFolder, 
                    string FTPFilePrefix, 
                    string TS360UserID, 
                    string TS360CartName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMARCProfiler/SendMARCFileFTP", ReplyAction="http://tempuri.org/IMARCProfiler/SendMARCFileFTPResponse")]
        System.Threading.Tasks.Task SendMARCFileFTPAsync(
                    string sortColumn, 
                    string basketSummaryID, 
                    string sortDirection, 
                    string ProfileID, 
                    string FullIndicator, 
                    bool isOrdered, 
                    bool isCancelled, 
                    bool isOCLCEnabled, 
                    bool isBTEmployee, 
                    bool hasInventoryRules, 
                    string marketType, 
                    string FTPServer, 
                    string FTPUserID, 
                    string FTPPassword, 
                    string FTPFolder, 
                    string FTPFilePrefix, 
                    string TS360UserID, 
                    string TS360CartName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMARCProfiler/SendMARCFileFTPTest", ReplyAction="http://tempuri.org/IMARCProfiler/SendMARCFileFTPTestResponse")]
        void SendMARCFileFTPTest(string FTPServer, string FTPUserID, string FTPPassword, string FTPFolder, string TS360UserID, string MarcProfilerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMARCProfiler/SendMARCFileFTPTest", ReplyAction="http://tempuri.org/IMARCProfiler/SendMARCFileFTPTestResponse")]
        System.Threading.Tasks.Task SendMARCFileFTPTestAsync(string FTPServer, string FTPUserID, string FTPPassword, string FTPFolder, string TS360UserID, string MarcProfilerID);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMARCProfiler/SendMARCFileSP")]
        void SendMARCFileSP(string sortColumn, string basketSummaryID, string sortDirection, string ProfileID, string FullIndicator, bool isOrdered, bool isCancelled, bool isOCLCEnabled, bool isBTEmployee, bool hasInventoryRules, string marketType, string TS360UserID, string TS360CartName, string ProfileName);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMARCProfiler/SendMARCFileSP")]
        System.Threading.Tasks.Task SendMARCFileSPAsync(string sortColumn, string basketSummaryID, string sortDirection, string ProfileID, string FullIndicator, bool isOrdered, bool isCancelled, bool isOCLCEnabled, bool isBTEmployee, bool hasInventoryRules, string marketType, string TS360UserID, string TS360CartName, string ProfileName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMARCProfilerChannel : BT.TS360API.ExternalServices.MARCProfilerService.IMARCProfiler, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MARCProfilerClient : System.ServiceModel.ClientBase<BT.TS360API.ExternalServices.MARCProfilerService.IMARCProfiler>, BT.TS360API.ExternalServices.MARCProfilerService.IMARCProfiler {
        
        public MARCProfilerClient() {
        }
        
        public MARCProfilerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MARCProfilerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MARCProfilerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MARCProfilerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetMARCFile(string sortColumn, string basketSummaryID, string sortDirection, string ProfileID, string FullIndicator, bool isOrdered, bool isCancelled, bool isOCLCEnabled, bool isBTEmployee, bool hasInventoryRules, string marketType) {
            return base.Channel.GetMARCFile(sortColumn, basketSummaryID, sortDirection, ProfileID, FullIndicator, isOrdered, isCancelled, isOCLCEnabled, isBTEmployee, hasInventoryRules, marketType);
        }
        
        public System.Threading.Tasks.Task<string> GetMARCFileAsync(string sortColumn, string basketSummaryID, string sortDirection, string ProfileID, string FullIndicator, bool isOrdered, bool isCancelled, bool isOCLCEnabled, bool isBTEmployee, bool hasInventoryRules, string marketType) {
            return base.Channel.GetMARCFileAsync(sortColumn, basketSummaryID, sortDirection, ProfileID, FullIndicator, isOrdered, isCancelled, isOCLCEnabled, isBTEmployee, hasInventoryRules, marketType);
        }
        
        public void SendMARCFileFTP(
                    string sortColumn, 
                    string basketSummaryID, 
                    string sortDirection, 
                    string ProfileID, 
                    string FullIndicator, 
                    bool isOrdered, 
                    bool isCancelled, 
                    bool isOCLCEnabled, 
                    bool isBTEmployee, 
                    bool hasInventoryRules, 
                    string marketType, 
                    string FTPServer, 
                    string FTPUserID, 
                    string FTPPassword, 
                    string FTPFolder, 
                    string FTPFilePrefix, 
                    string TS360UserID, 
                    string TS360CartName) {
            base.Channel.SendMARCFileFTP(sortColumn, basketSummaryID, sortDirection, ProfileID, FullIndicator, isOrdered, isCancelled, isOCLCEnabled, isBTEmployee, hasInventoryRules, marketType, FTPServer, FTPUserID, FTPPassword, FTPFolder, FTPFilePrefix, TS360UserID, TS360CartName);
        }
        
        public System.Threading.Tasks.Task SendMARCFileFTPAsync(
                    string sortColumn, 
                    string basketSummaryID, 
                    string sortDirection, 
                    string ProfileID, 
                    string FullIndicator, 
                    bool isOrdered, 
                    bool isCancelled, 
                    bool isOCLCEnabled, 
                    bool isBTEmployee, 
                    bool hasInventoryRules, 
                    string marketType, 
                    string FTPServer, 
                    string FTPUserID, 
                    string FTPPassword, 
                    string FTPFolder, 
                    string FTPFilePrefix, 
                    string TS360UserID, 
                    string TS360CartName) {
            return base.Channel.SendMARCFileFTPAsync(sortColumn, basketSummaryID, sortDirection, ProfileID, FullIndicator, isOrdered, isCancelled, isOCLCEnabled, isBTEmployee, hasInventoryRules, marketType, FTPServer, FTPUserID, FTPPassword, FTPFolder, FTPFilePrefix, TS360UserID, TS360CartName);
        }
        
        public void SendMARCFileFTPTest(string FTPServer, string FTPUserID, string FTPPassword, string FTPFolder, string TS360UserID, string MarcProfilerID) {
            base.Channel.SendMARCFileFTPTest(FTPServer, FTPUserID, FTPPassword, FTPFolder, TS360UserID, MarcProfilerID);
        }
        
        public System.Threading.Tasks.Task SendMARCFileFTPTestAsync(string FTPServer, string FTPUserID, string FTPPassword, string FTPFolder, string TS360UserID, string MarcProfilerID) {
            return base.Channel.SendMARCFileFTPTestAsync(FTPServer, FTPUserID, FTPPassword, FTPFolder, TS360UserID, MarcProfilerID);
        }
        
        public void SendMARCFileSP(string sortColumn, string basketSummaryID, string sortDirection, string ProfileID, string FullIndicator, bool isOrdered, bool isCancelled, bool isOCLCEnabled, bool isBTEmployee, bool hasInventoryRules, string marketType, string TS360UserID, string TS360CartName, string ProfileName) {
            base.Channel.SendMARCFileSP(sortColumn, basketSummaryID, sortDirection, ProfileID, FullIndicator, isOrdered, isCancelled, isOCLCEnabled, isBTEmployee, hasInventoryRules, marketType, TS360UserID, TS360CartName, ProfileName);
        }
        
        public System.Threading.Tasks.Task SendMARCFileSPAsync(string sortColumn, string basketSummaryID, string sortDirection, string ProfileID, string FullIndicator, bool isOrdered, bool isCancelled, bool isOCLCEnabled, bool isBTEmployee, bool hasInventoryRules, string marketType, string TS360UserID, string TS360CartName, string ProfileName) {
            return base.Channel.SendMARCFileSPAsync(sortColumn, basketSummaryID, sortDirection, ProfileID, FullIndicator, isOrdered, isCancelled, isOCLCEnabled, isBTEmployee, hasInventoryRules, marketType, TS360UserID, TS360CartName, ProfileName);
        }
    }
}
