CREATE PROCEDURE [dbo].[bts_removesprocs]
AS
	if exists (select * from sysobjects where id = object_id(N'[dbo].[bts_PartnerMgmtValidator]') and OBJECTPROPERTY(id, N'IsProcedure') = 1) drop procedure [dbo].[bts_PartnerMgmtValidator]
	if exists (select * from sysobjects where id = object_id(N'[dbo].[bts_validate_unenlisted_sendport]') and OBJECTPROPERTY(id, N'IsProcedure') = 1) drop procedure [dbo].[bts_validate_unenlisted_sendport]
	if exists (select * from sysobjects where id = object_id(N'[dbo].[bts_validate_unenlisted_sendportgroup]') and OBJECTPROPERTY(id, N'IsProcedure') = 1) drop procedure [dbo].[bts_validate_unenlisted_sendportgroup]
	if exists (select * from sysobjects where id = object_id(N'[dbo].[bts_validate_stopped_orchestration]') and OBJECTPROPERTY(id, N'IsProcedure') = 1) drop procedure [dbo].[bts_validate_stopped_orchestration]
	if exists (select * from sysobjects where id = object_id(N'[dbo].[bts_validate_started_orchestration]') and OBJECTPROPERTY(id, N'IsProcedure') = 1) drop procedure [dbo].[bts_validate_started_orchestration]
	if exists (select * from sysobjects where id = object_id(N'[dbo].[bts_validate_started_sendportgroup]') and OBJECTPROPERTY(id, N'IsProcedure') = 1) drop procedure [dbo].[bts_validate_started_sendportgroup]
	if exists (select * from sysobjects where id = object_id(N'[dbo].[bts_validate_enlisted_parties]') and OBJECTPROPERTY(id, N'IsProcedure') = 1) drop procedure [dbo].[bts_validate_enlisted_parties]
	if exists (select * from sysobjects where id = object_id(N'[dbo].[bts_ReceiveLocation_Status_Update]') and OBJECTPROPERTY(id, N'IsProcedure') = 1) drop procedure [dbo].[bts_ReceiveLocation_Status_Update]
	if exists (select * from sysobjects where id = object_id(N'[dbo].[bts_SendPort_Status_Update]') and OBJECTPROPERTY(id, N'IsProcedure') = 1) drop procedure [dbo].[bts_SendPort_Status_Update]
	if exists (select * from sysobjects where id = object_id(N'[dbo].[bts_SendPortGroup_Status_Update]') and OBJECTPROPERTY(id, N'IsProcedure') = 1) drop procedure [dbo].[bts_SendPortGroup_Status_Update]
	if exists (select * from sysobjects where id = object_id(N'[dbo].[bts_Orchestration_Status_Update]') and OBJECTPROPERTY(id, N'IsProcedure') = 1) drop procedure [dbo].[bts_Orchestration_Status_Update]
	if exists (select * from sysobjects where id = object_id(N'[dbo].[bts_ReceivePort_Timestamp_Update]') and OBJECTPROPERTY(id, N'IsProcedure') = 1) drop procedure [dbo].[bts_ReceivePort_Timestamp_Update]	
	if exists (select * from sysobjects where id = object_id(N'[dbo].[bts_RoleInfoFromPortMappingId]') and OBJECTPROPERTY(id, N'IsProcedure') = 1) drop procedure [dbo].[bts_RoleInfoFromPortMappingId]	
	if exists (select * from sysobjects where id = object_id(N'[dbo].[bts_schema_description_update]') and OBJECTPROPERTY(id, N'IsProcedure') = 1) drop procedure [dbo].[bts_schema_description_update]	
	if exists (select * from sysobjects where id = object_id(N'[dbo].[bts_transform_description_update]') and OBJECTPROPERTY(id, N'IsProcedure') = 1) drop procedure [dbo].[bts_transform_description_update]	
