//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

using BT.ILSQueue.Business.Helpers;

namespace BT.ILSQueue.Business.MARCProfilerReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IMARCProfiler", Namespace="http://tempuri.org/")]
    public partial class MARCProfiler : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetMARCFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMARCFileFTPOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMARCFileFTPTestOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMARCFileSPOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MARCProfiler() {
            this.Url = GetMARCWebServiceURL();
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }

            this.Timeout = GetTimeout();
        }

        private string GetMARCWebServiceURL()
        {
            var marcUrl = AppConfigHelper.RetriveAppSettings<string>(AppConfigHelper.MARC_SERVICE_URL);
            if (marcUrl != null)
            {
                return marcUrl;
            }
            return string.Empty;
        }

        private int GetTimeout()
        {
            var marcTimeout = AppConfigHelper.RetriveAppSettings<int>(AppConfigHelper.MARC_SERVICE_TIMEOUT);
            
            return marcTimeout * 60 * 1000;
        }

        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetMARCFileCompletedEventHandler GetMARCFileCompleted;
        
        /// <remarks/>
        public event SendMARCFileFTPCompletedEventHandler SendMARCFileFTPCompleted;
        
        /// <remarks/>
        public event SendMARCFileFTPTestCompletedEventHandler SendMARCFileFTPTestCompleted;
        
        /// <remarks/>
        public event SendMARCFileSPCompletedEventHandler SendMARCFileSPCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMARCProfiler/GetMARCFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetMARCFile(
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sortColumn, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string basketSummaryID, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sortDirection, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ProfileID, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string FullIndicator, 
                    bool isOrdered, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] bool isOrderedSpecified, 
                    bool isCancelled, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] bool isCancelledSpecified, 
                    bool isOCLCEnabled, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] bool isOCLCEnabledSpecified, 
                    bool isBTEmployee, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] bool isBTEmployeeSpecified, 
                    bool hasInventoryRules, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] bool hasInventoryRulesSpecified, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string marketType) {
            object[] results = this.Invoke("GetMARCFile", new object[] {
                        sortColumn,
                        basketSummaryID,
                        sortDirection,
                        ProfileID,
                        FullIndicator,
                        isOrdered,
                        isOrderedSpecified,
                        isCancelled,
                        isCancelledSpecified,
                        isOCLCEnabled,
                        isOCLCEnabledSpecified,
                        isBTEmployee,
                        isBTEmployeeSpecified,
                        hasInventoryRules,
                        hasInventoryRulesSpecified,
                        marketType});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetMARCFileAsync(
                    string sortColumn, 
                    string basketSummaryID, 
                    string sortDirection, 
                    string ProfileID, 
                    string FullIndicator, 
                    bool isOrdered, 
                    bool isOrderedSpecified, 
                    bool isCancelled, 
                    bool isCancelledSpecified, 
                    bool isOCLCEnabled, 
                    bool isOCLCEnabledSpecified, 
                    bool isBTEmployee, 
                    bool isBTEmployeeSpecified, 
                    bool hasInventoryRules, 
                    bool hasInventoryRulesSpecified, 
                    string marketType) {
            this.GetMARCFileAsync(sortColumn, basketSummaryID, sortDirection, ProfileID, FullIndicator, isOrdered, isOrderedSpecified, isCancelled, isCancelledSpecified, isOCLCEnabled, isOCLCEnabledSpecified, isBTEmployee, isBTEmployeeSpecified, hasInventoryRules, hasInventoryRulesSpecified, marketType, null);
        }
        
        /// <remarks/>
        public void GetMARCFileAsync(
                    string sortColumn, 
                    string basketSummaryID, 
                    string sortDirection, 
                    string ProfileID, 
                    string FullIndicator, 
                    bool isOrdered, 
                    bool isOrderedSpecified, 
                    bool isCancelled, 
                    bool isCancelledSpecified, 
                    bool isOCLCEnabled, 
                    bool isOCLCEnabledSpecified, 
                    bool isBTEmployee, 
                    bool isBTEmployeeSpecified, 
                    bool hasInventoryRules, 
                    bool hasInventoryRulesSpecified, 
                    string marketType, 
                    object userState) {
            if ((this.GetMARCFileOperationCompleted == null)) {
                this.GetMARCFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMARCFileOperationCompleted);
            }
            this.InvokeAsync("GetMARCFile", new object[] {
                        sortColumn,
                        basketSummaryID,
                        sortDirection,
                        ProfileID,
                        FullIndicator,
                        isOrdered,
                        isOrderedSpecified,
                        isCancelled,
                        isCancelledSpecified,
                        isOCLCEnabled,
                        isOCLCEnabledSpecified,
                        isBTEmployee,
                        isBTEmployeeSpecified,
                        hasInventoryRules,
                        hasInventoryRulesSpecified,
                        marketType}, this.GetMARCFileOperationCompleted, userState);
        }
        
        private void OnGetMARCFileOperationCompleted(object arg) {
            if ((this.GetMARCFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMARCFileCompleted(this, new GetMARCFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMARCProfiler/SendMARCFileFTP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendMARCFileFTP(
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sortColumn, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string basketSummaryID, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sortDirection, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ProfileID, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string FullIndicator, 
                    bool isOrdered, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] bool isOrderedSpecified, 
                    bool isCancelled, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] bool isCancelledSpecified, 
                    bool isOCLCEnabled, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] bool isOCLCEnabledSpecified, 
                    bool isBTEmployee, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] bool isBTEmployeeSpecified, 
                    bool hasInventoryRules, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] bool hasInventoryRulesSpecified, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string marketType, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string FTPServer, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string FTPUserID, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string FTPPassword, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string FTPFolder, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string FTPFilePrefix, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string TS360UserID, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string TS360CartName) {
            this.Invoke("SendMARCFileFTP", new object[] {
                        sortColumn,
                        basketSummaryID,
                        sortDirection,
                        ProfileID,
                        FullIndicator,
                        isOrdered,
                        isOrderedSpecified,
                        isCancelled,
                        isCancelledSpecified,
                        isOCLCEnabled,
                        isOCLCEnabledSpecified,
                        isBTEmployee,
                        isBTEmployeeSpecified,
                        hasInventoryRules,
                        hasInventoryRulesSpecified,
                        marketType,
                        FTPServer,
                        FTPUserID,
                        FTPPassword,
                        FTPFolder,
                        FTPFilePrefix,
                        TS360UserID,
                        TS360CartName});
        }
        
        /// <remarks/>
        public void SendMARCFileFTPAsync(
                    string sortColumn, 
                    string basketSummaryID, 
                    string sortDirection, 
                    string ProfileID, 
                    string FullIndicator, 
                    bool isOrdered, 
                    bool isOrderedSpecified, 
                    bool isCancelled, 
                    bool isCancelledSpecified, 
                    bool isOCLCEnabled, 
                    bool isOCLCEnabledSpecified, 
                    bool isBTEmployee, 
                    bool isBTEmployeeSpecified, 
                    bool hasInventoryRules, 
                    bool hasInventoryRulesSpecified, 
                    string marketType, 
                    string FTPServer, 
                    string FTPUserID, 
                    string FTPPassword, 
                    string FTPFolder, 
                    string FTPFilePrefix, 
                    string TS360UserID, 
                    string TS360CartName) {
            this.SendMARCFileFTPAsync(sortColumn, basketSummaryID, sortDirection, ProfileID, FullIndicator, isOrdered, isOrderedSpecified, isCancelled, isCancelledSpecified, isOCLCEnabled, isOCLCEnabledSpecified, isBTEmployee, isBTEmployeeSpecified, hasInventoryRules, hasInventoryRulesSpecified, marketType, FTPServer, FTPUserID, FTPPassword, FTPFolder, FTPFilePrefix, TS360UserID, TS360CartName, null);
        }
        
        /// <remarks/>
        public void SendMARCFileFTPAsync(
                    string sortColumn, 
                    string basketSummaryID, 
                    string sortDirection, 
                    string ProfileID, 
                    string FullIndicator, 
                    bool isOrdered, 
                    bool isOrderedSpecified, 
                    bool isCancelled, 
                    bool isCancelledSpecified, 
                    bool isOCLCEnabled, 
                    bool isOCLCEnabledSpecified, 
                    bool isBTEmployee, 
                    bool isBTEmployeeSpecified, 
                    bool hasInventoryRules, 
                    bool hasInventoryRulesSpecified, 
                    string marketType, 
                    string FTPServer, 
                    string FTPUserID, 
                    string FTPPassword, 
                    string FTPFolder, 
                    string FTPFilePrefix, 
                    string TS360UserID, 
                    string TS360CartName, 
                    object userState) {
            if ((this.SendMARCFileFTPOperationCompleted == null)) {
                this.SendMARCFileFTPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMARCFileFTPOperationCompleted);
            }
            this.InvokeAsync("SendMARCFileFTP", new object[] {
                        sortColumn,
                        basketSummaryID,
                        sortDirection,
                        ProfileID,
                        FullIndicator,
                        isOrdered,
                        isOrderedSpecified,
                        isCancelled,
                        isCancelledSpecified,
                        isOCLCEnabled,
                        isOCLCEnabledSpecified,
                        isBTEmployee,
                        isBTEmployeeSpecified,
                        hasInventoryRules,
                        hasInventoryRulesSpecified,
                        marketType,
                        FTPServer,
                        FTPUserID,
                        FTPPassword,
                        FTPFolder,
                        FTPFilePrefix,
                        TS360UserID,
                        TS360CartName}, this.SendMARCFileFTPOperationCompleted, userState);
        }
        
        private void OnSendMARCFileFTPOperationCompleted(object arg) {
            if ((this.SendMARCFileFTPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMARCFileFTPCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMARCProfiler/SendMARCFileFTPTest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendMARCFileFTPTest([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string FTPServer, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string FTPUserID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string FTPPassword, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string FTPFolder, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string TS360UserID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string MarcProfilerID) {
            this.Invoke("SendMARCFileFTPTest", new object[] {
                        FTPServer,
                        FTPUserID,
                        FTPPassword,
                        FTPFolder,
                        TS360UserID,
                        MarcProfilerID});
        }
        
        /// <remarks/>
        public void SendMARCFileFTPTestAsync(string FTPServer, string FTPUserID, string FTPPassword, string FTPFolder, string TS360UserID, string MarcProfilerID) {
            this.SendMARCFileFTPTestAsync(FTPServer, FTPUserID, FTPPassword, FTPFolder, TS360UserID, MarcProfilerID, null);
        }
        
        /// <remarks/>
        public void SendMARCFileFTPTestAsync(string FTPServer, string FTPUserID, string FTPPassword, string FTPFolder, string TS360UserID, string MarcProfilerID, object userState) {
            if ((this.SendMARCFileFTPTestOperationCompleted == null)) {
                this.SendMARCFileFTPTestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMARCFileFTPTestOperationCompleted);
            }
            this.InvokeAsync("SendMARCFileFTPTest", new object[] {
                        FTPServer,
                        FTPUserID,
                        FTPPassword,
                        FTPFolder,
                        TS360UserID,
                        MarcProfilerID}, this.SendMARCFileFTPTestOperationCompleted, userState);
        }
        
        private void OnSendMARCFileFTPTestOperationCompleted(object arg) {
            if ((this.SendMARCFileFTPTestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMARCFileFTPTestCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMARCProfiler/SendMARCFileSP", RequestNamespace="http://tempuri.org/", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendMARCFileSP(
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sortColumn, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string basketSummaryID, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sortDirection, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ProfileID, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string FullIndicator, 
                    bool isOrdered, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] bool isOrderedSpecified, 
                    bool isCancelled, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] bool isCancelledSpecified, 
                    bool isOCLCEnabled, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] bool isOCLCEnabledSpecified, 
                    bool isBTEmployee, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] bool isBTEmployeeSpecified, 
                    bool hasInventoryRules, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] bool hasInventoryRulesSpecified, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string marketType, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string TS360UserID, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string TS360CartName, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ProfileName) {
            this.Invoke("SendMARCFileSP", new object[] {
                        sortColumn,
                        basketSummaryID,
                        sortDirection,
                        ProfileID,
                        FullIndicator,
                        isOrdered,
                        isOrderedSpecified,
                        isCancelled,
                        isCancelledSpecified,
                        isOCLCEnabled,
                        isOCLCEnabledSpecified,
                        isBTEmployee,
                        isBTEmployeeSpecified,
                        hasInventoryRules,
                        hasInventoryRulesSpecified,
                        marketType,
                        TS360UserID,
                        TS360CartName,
                        ProfileName});
        }
        
        /// <remarks/>
        public void SendMARCFileSPAsync(
                    string sortColumn, 
                    string basketSummaryID, 
                    string sortDirection, 
                    string ProfileID, 
                    string FullIndicator, 
                    bool isOrdered, 
                    bool isOrderedSpecified, 
                    bool isCancelled, 
                    bool isCancelledSpecified, 
                    bool isOCLCEnabled, 
                    bool isOCLCEnabledSpecified, 
                    bool isBTEmployee, 
                    bool isBTEmployeeSpecified, 
                    bool hasInventoryRules, 
                    bool hasInventoryRulesSpecified, 
                    string marketType, 
                    string TS360UserID, 
                    string TS360CartName, 
                    string ProfileName) {
            this.SendMARCFileSPAsync(sortColumn, basketSummaryID, sortDirection, ProfileID, FullIndicator, isOrdered, isOrderedSpecified, isCancelled, isCancelledSpecified, isOCLCEnabled, isOCLCEnabledSpecified, isBTEmployee, isBTEmployeeSpecified, hasInventoryRules, hasInventoryRulesSpecified, marketType, TS360UserID, TS360CartName, ProfileName, null);
        }
        
        /// <remarks/>
        public void SendMARCFileSPAsync(
                    string sortColumn, 
                    string basketSummaryID, 
                    string sortDirection, 
                    string ProfileID, 
                    string FullIndicator, 
                    bool isOrdered, 
                    bool isOrderedSpecified, 
                    bool isCancelled, 
                    bool isCancelledSpecified, 
                    bool isOCLCEnabled, 
                    bool isOCLCEnabledSpecified, 
                    bool isBTEmployee, 
                    bool isBTEmployeeSpecified, 
                    bool hasInventoryRules, 
                    bool hasInventoryRulesSpecified, 
                    string marketType, 
                    string TS360UserID, 
                    string TS360CartName, 
                    string ProfileName, 
                    object userState) {
            if ((this.SendMARCFileSPOperationCompleted == null)) {
                this.SendMARCFileSPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMARCFileSPOperationCompleted);
            }
            this.InvokeAsync("SendMARCFileSP", new object[] {
                        sortColumn,
                        basketSummaryID,
                        sortDirection,
                        ProfileID,
                        FullIndicator,
                        isOrdered,
                        isOrderedSpecified,
                        isCancelled,
                        isCancelledSpecified,
                        isOCLCEnabled,
                        isOCLCEnabledSpecified,
                        isBTEmployee,
                        isBTEmployeeSpecified,
                        hasInventoryRules,
                        hasInventoryRulesSpecified,
                        marketType,
                        TS360UserID,
                        TS360CartName,
                        ProfileName}, this.SendMARCFileSPOperationCompleted, userState);
        }
        
        private void OnSendMARCFileSPOperationCompleted(object arg) {
            if ((this.SendMARCFileSPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMARCFileSPCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetMARCFileCompletedEventHandler(object sender, GetMARCFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMARCFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMARCFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void SendMARCFileFTPCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void SendMARCFileFTPTestCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void SendMARCFileSPCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591