'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=4.0.30319.1.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="BTNextGen.ESP.DistributionRequest"),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="BTNextGen.ESP.DistributionRequest", IsNullable:=false)>  _
Partial Public Class DistributionRequests
    
    Private distributionRequestField() As DistributionRequestsDistributionRequest
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("DistributionRequest")>  _
    Public Property DistributionRequest() As DistributionRequestsDistributionRequest()
        Get
            Return Me.distributionRequestField
        End Get
        Set
            Me.distributionRequestField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="BTNextGen.ESP.DistributionRequest")>  _
Partial Public Class DistributionRequestsDistributionRequest
    
    Private eSPLibraryIDField As String
    
    Private userNameField As String
    
    Private userGuidField As String
    
    Private cartIDField As String
    
    Private basketNameField As String
    
    Private fundMonitoringField As String
    
    Private itemsField() As DistributionRequestsDistributionRequestItems
    
    Private branchesField() As DistributionRequestsDistributionRequestBranches
    
    '''<remarks/>
    Public Property ESPLibraryID() As String
        Get
            Return Me.eSPLibraryIDField
        End Get
        Set
            Me.eSPLibraryIDField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property UserName() As String
        Get
            Return Me.userNameField
        End Get
        Set
            Me.userNameField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property UserGuid() As String
        Get
            Return Me.userGuidField
        End Get
        Set
            Me.userGuidField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property CartID() As String
        Get
            Return Me.cartIDField
        End Get
        Set
            Me.cartIDField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property BasketName() As String
        Get
            Return Me.basketNameField
        End Get
        Set
            Me.basketNameField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property FundMonitoring() As String
        Get
            Return Me.fundMonitoringField
        End Get
        Set
            Me.fundMonitoringField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("items", IsNullable:=false)>  _
    Public Property Items() As DistributionRequestsDistributionRequestItems()
        Get
            Return Me.itemsField
        End Get
        Set
            Me.itemsField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("branches", IsNullable:=false)>  _
    Public Property Branches() As DistributionRequestsDistributionRequestBranches()
        Get
            Return Me.branchesField
        End Get
        Set
            Me.branchesField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="BTNextGen.ESP.DistributionRequest")>  _
Partial Public Class DistributionRequestsDistributionRequestItems
    
    Private lineItemIDField As String
    
    Private bTKeyField As String
    
    Private fundidField As String
    
    Private fundcodeField As String
    
    Private priceField As String
    
    Private quantityField As String

    Private bisacField As String
    
    '''<remarks/>
    Public Property LineItemID() As String
        Get
            Return Me.lineItemIDField
        End Get
        Set
            Me.lineItemIDField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property BTKey() As String
        Get
            Return Me.bTKeyField
        End Get
        Set
            Me.bTKeyField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property fundid() As String
        Get
            Return Me.fundidField
        End Get
        Set
            Me.fundidField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property fundcode() As String
        Get
            Return Me.fundcodeField
        End Get
        Set
            Me.fundcodeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property price() As String
        Get
            Return Me.priceField
        End Get
        Set
            Me.priceField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property quantity() As String
        Get
            Return Me.quantityField
        End Get
        Set
            Me.quantityField = value
        End Set
    End Property

    Public Property bisac() As String
        Get
            Return Me.bisacField
        End Get
        Set(value As String)
            Me.bisacField = value
        End Set
    End Property

End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="BTNextGen.ESP.DistributionRequest")>  _
Partial Public Class DistributionRequestsDistributionRequestBranches
    
    Private branchidField As String
    
    Private codeField As String
    
    '''<remarks/>
    Public Property branchid() As String
        Get
            Return Me.branchidField
        End Get
        Set
            Me.branchidField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property code() As String
        Get
            Return Me.codeField
        End Get
        Set
            Me.codeField = value
        End Set
    End Property
End Class
