'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=4.0.30319.1.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
Partial Public Class AppData
    
    Private emailRecipientsField() As AppDataEmailRecipient
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("EmailRecipient", IsNullable:=false)>  _
    Public Property EmailRecipients() As AppDataEmailRecipient()
        Get
            Return Me.emailRecipientsField
        End Get
        Set
            Me.emailRecipientsField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class AppDataEmailRecipient
    
    Private nameField As String
    
    Private emailAddressField As String
    
    Private groupField() As String
    
    '''<remarks/>
    Public Property Name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property EmailAddress() As String
        Get
            Return Me.emailAddressField
        End Get
        Set
            Me.emailAddressField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Group")>  _
    Public Property Group() As String()
        Get
            Return Me.groupField
        End Get
        Set
            Me.groupField = value
        End Set
    End Property
End Class
