'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=4.0.30319.1.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="BTNextGen.ESP.RankRequest"),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="BTNextGen.ESP.RankRequest", IsNullable:=false)>  _
Partial Public Class RankRequests
    
    Private rankRequestField() As RankRequestsRankRequest
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("RankRequest")>  _
    Public Property RankRequest() As RankRequestsRankRequest()
        Get
            Return Me.rankRequestField
        End Get
        Set
            Me.rankRequestField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="BTNextGen.ESP.RankRequest")>  _
Partial Public Class RankRequestsRankRequest
    
    Private eSPLibraryIDField As String
    
    Private userNameField As String
    
    Private userGuidField As String
    
    Private cartIDField As String
    
    Private basketNameField As String
    
    Private detailField() As RankRequestsRankRequestItems
    
    '''<remarks/>
    Public Property ESPLibraryID() As String
        Get
            Return Me.eSPLibraryIDField
        End Get
        Set
            Me.eSPLibraryIDField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property UserName() As String
        Get
            Return Me.userNameField
        End Get
        Set
            Me.userNameField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property UserGuid() As String
        Get
            Return Me.userGuidField
        End Get
        Set
            Me.userGuidField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property CartID() As String
        Get
            Return Me.cartIDField
        End Get
        Set
            Me.cartIDField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property BasketName() As String
        Get
            Return Me.basketNameField
        End Get
        Set
            Me.basketNameField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("items", IsNullable:=false)>  _
    Public Property Detail() As RankRequestsRankRequestItems()
        Get
            Return Me.detailField
        End Get
        Set
            Me.detailField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="BTNextGen.ESP.RankRequest")>  _
Partial Public Class RankRequestsRankRequestItems
    
    Private lineItemIDField As String
    
    Private bTKeyField As String

    Private bisacField As String
    '''<remarks/>
    Public Property LineItemID() As String
        Get
            Return Me.lineItemIDField
        End Get
        Set
            Me.lineItemIDField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property BTKey() As String
        Get
            Return Me.bTKeyField
        End Get
        Set(value As String)
            Me.bTKeyField = Value
        End Set
    End Property

    Public Property bisac() As String
        Get
            Return Me.bisacField
        End Get
        Set(value As String)
            Me.bisacField = value
        End Set
    End Property
End Class
