//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace BT.TS360API.Common.BTPricingService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BTPricingServiceSoap", Namespace="http://edi.btol.com/")]
    public partial class BTPricingService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PricingRequestByParametersOperationCompleted;
        
        private System.Threading.SendOrPostCallback PricingRequestByClassOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BTPricingService() {
            this.Url = global::BT.TS360API.Common.Properties.Settings.Default.BT_TS360API_Common_BTPricingService_BTPricingService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PricingRequestByParametersCompletedEventHandler PricingRequestByParametersCompleted;
        
        /// <remarks/>
        public event PricingRequestByClassCompletedEventHandler PricingRequestByClassCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://edi.btol.com/PricingRequestByParameters", RequestNamespace="http://edi.btol.com/", ResponseNamespace="http://edi.btol.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PricingResponse PricingRequestByParameters(string SystemID, string SystemPassword, string AccountID, string WHSCode, string ItemID, string Quantity, string ReturnFlag, string PriceKey, string ProductLine, string ListPrice, string AcceptableDiscount) {
            object[] results = this.Invoke("PricingRequestByParameters", new object[] {
                        SystemID,
                        SystemPassword,
                        AccountID,
                        WHSCode,
                        ItemID,
                        Quantity,
                        ReturnFlag,
                        PriceKey,
                        ProductLine,
                        ListPrice,
                        AcceptableDiscount});
            return ((PricingResponse)(results[0]));
        }
        
        /// <remarks/>
        public void PricingRequestByParametersAsync(string SystemID, string SystemPassword, string AccountID, string WHSCode, string ItemID, string Quantity, string ReturnFlag, string PriceKey, string ProductLine, string ListPrice, string AcceptableDiscount) {
            this.PricingRequestByParametersAsync(SystemID, SystemPassword, AccountID, WHSCode, ItemID, Quantity, ReturnFlag, PriceKey, ProductLine, ListPrice, AcceptableDiscount, null);
        }
        
        /// <remarks/>
        public void PricingRequestByParametersAsync(string SystemID, string SystemPassword, string AccountID, string WHSCode, string ItemID, string Quantity, string ReturnFlag, string PriceKey, string ProductLine, string ListPrice, string AcceptableDiscount, object userState) {
            if ((this.PricingRequestByParametersOperationCompleted == null)) {
                this.PricingRequestByParametersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPricingRequestByParametersOperationCompleted);
            }
            this.InvokeAsync("PricingRequestByParameters", new object[] {
                        SystemID,
                        SystemPassword,
                        AccountID,
                        WHSCode,
                        ItemID,
                        Quantity,
                        ReturnFlag,
                        PriceKey,
                        ProductLine,
                        ListPrice,
                        AcceptableDiscount}, this.PricingRequestByParametersOperationCompleted, userState);
        }
        
        private void OnPricingRequestByParametersOperationCompleted(object arg) {
            if ((this.PricingRequestByParametersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PricingRequestByParametersCompleted(this, new PricingRequestByParametersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://edi.btol.com/PricingRequestByClass", RequestNamespace="http://edi.btol.com/", ResponseNamespace="http://edi.btol.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PricingResponse PricingRequestByClass(PricingRequest RequestClass) {
            object[] results = this.Invoke("PricingRequestByClass", new object[] {
                        RequestClass});
            return ((PricingResponse)(results[0]));
        }
        
        /// <remarks/>
        public void PricingRequestByClassAsync(PricingRequest RequestClass) {
            this.PricingRequestByClassAsync(RequestClass, null);
        }
        
        /// <remarks/>
        public void PricingRequestByClassAsync(PricingRequest RequestClass, object userState) {
            if ((this.PricingRequestByClassOperationCompleted == null)) {
                this.PricingRequestByClassOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPricingRequestByClassOperationCompleted);
            }
            this.InvokeAsync("PricingRequestByClass", new object[] {
                        RequestClass}, this.PricingRequestByClassOperationCompleted, userState);
        }
        
        private void OnPricingRequestByClassOperationCompleted(object arg) {
            if ((this.PricingRequestByClassCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PricingRequestByClassCompleted(this, new PricingRequestByClassCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edi.btol.com/")]
    public partial class PricingResponse {
        
        private string statusMessageField;
        
        private string accountIDField;
        
        private string wHSCodeField;
        
        private int itemCountField;
        
        private ItemResponseDetail[] itemsListField;
        
        /// <remarks/>
        public string StatusMessage {
            get {
                return this.statusMessageField;
            }
            set {
                this.statusMessageField = value;
            }
        }
        
        /// <remarks/>
        public string AccountID {
            get {
                return this.accountIDField;
            }
            set {
                this.accountIDField = value;
            }
        }
        
        /// <remarks/>
        public string WHSCode {
            get {
                return this.wHSCodeField;
            }
            set {
                this.wHSCodeField = value;
            }
        }
        
        /// <remarks/>
        public int ItemCount {
            get {
                return this.itemCountField;
            }
            set {
                this.itemCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Item")]
        public ItemResponseDetail[] ItemsList {
            get {
                return this.itemsListField;
            }
            set {
                this.itemsListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edi.btol.com/")]
    public partial class ItemResponseDetail {
        
        private string itemIDField;
        
        private string itemTypeField;
        
        private decimal discountPercentField;
        
        private decimal discountPriceField;
        
        private string lineStatusMessageField;
        
        /// <remarks/>
        public string ItemID {
            get {
                return this.itemIDField;
            }
            set {
                this.itemIDField = value;
            }
        }
        
        /// <remarks/>
        public string ItemType {
            get {
                return this.itemTypeField;
            }
            set {
                this.itemTypeField = value;
            }
        }
        
        /// <remarks/>
        public decimal DiscountPercent {
            get {
                return this.discountPercentField;
            }
            set {
                this.discountPercentField = value;
            }
        }
        
        /// <remarks/>
        public decimal DiscountPrice {
            get {
                return this.discountPriceField;
            }
            set {
                this.discountPriceField = value;
            }
        }
        
        /// <remarks/>
        public string LineStatusMessage {
            get {
                return this.lineStatusMessageField;
            }
            set {
                this.lineStatusMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edi.btol.com/")]
    public partial class ItemRequestDetail {
        
        private string itemIdField;
        
        private int quantityField;
        
        private string returnFlagField;
        
        private string priceKeyField;
        
        private string productLineField;
        
        private decimal listPriceField;
        
        private decimal acceptableDiscountField;
        
        /// <remarks/>
        public string ItemId {
            get {
                return this.itemIdField;
            }
            set {
                this.itemIdField = value;
            }
        }
        
        /// <remarks/>
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public string ReturnFlag {
            get {
                return this.returnFlagField;
            }
            set {
                this.returnFlagField = value;
            }
        }
        
        /// <remarks/>
        public string PriceKey {
            get {
                return this.priceKeyField;
            }
            set {
                this.priceKeyField = value;
            }
        }
        
        /// <remarks/>
        public string ProductLine {
            get {
                return this.productLineField;
            }
            set {
                this.productLineField = value;
            }
        }
        
        /// <remarks/>
        public decimal ListPrice {
            get {
                return this.listPriceField;
            }
            set {
                this.listPriceField = value;
            }
        }
        
        /// <remarks/>
        public decimal AcceptableDiscount {
            get {
                return this.acceptableDiscountField;
            }
            set {
                this.acceptableDiscountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edi.btol.com/")]
    public partial class PricingRequest {
        
        private string systemIDField;
        
        private string systemPasswordField;
        
        private string accountIDField;
        
        private string wHSCODField;
        
        private ItemRequestDetail[] itemListField;
        
        /// <remarks/>
        public string SystemID {
            get {
                return this.systemIDField;
            }
            set {
                this.systemIDField = value;
            }
        }
        
        /// <remarks/>
        public string SystemPassword {
            get {
                return this.systemPasswordField;
            }
            set {
                this.systemPasswordField = value;
            }
        }
        
        /// <remarks/>
        public string AccountID {
            get {
                return this.accountIDField;
            }
            set {
                this.accountIDField = value;
            }
        }
        
        /// <remarks/>
        public string WHSCOD {
            get {
                return this.wHSCODField;
            }
            set {
                this.wHSCODField = value;
            }
        }
        
        /// <remarks/>
        public ItemRequestDetail[] ItemList {
            get {
                return this.itemListField;
            }
            set {
                this.itemListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void PricingRequestByParametersCompletedEventHandler(object sender, PricingRequestByParametersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PricingRequestByParametersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PricingRequestByParametersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PricingResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PricingResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void PricingRequestByClassCompletedEventHandler(object sender, PricingRequestByClassCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PricingRequestByClassCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PricingRequestByClassCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PricingResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PricingResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591