//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute("cXML",Namespace="", IsNullable=false)]
//[XmlRoot("cXML")]
public partial class cXML {
    
     

    private cXMLHeader headerField;
    
    private cXMLRequest requestField;

    private cXMLResponse responseField;
    
    private string payloadIDField;
    
    private string timestampField;
    
    private string versionField;
    
    private string langField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string payloadID
    {
        get
        {
            return this.payloadIDField;
        }
        set
        {
            this.payloadIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string timestamp
    {
        get
        {
            return this.timestampField;
        }
        set
        {
            this.timestampField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version
    {
        get
        {
            return this.versionField;
        }
        set
        {
            this.versionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
    public string lang
    {
        get
        {
            return this.langField;
        }
        set
        {
            this.langField = value;
        }
    }



    /// <remarks/>
    public cXMLHeader Header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
    
    /// <remarks/>
    public cXMLRequest Request {
        get {
            return this.requestField;
        }
        set {
            this.requestField = value;
        }
    }

    public cXMLResponse Response
    {
        get
        {
            return this.responseField;
        }
        set
        {
            this.responseField = value;
        }
    }

}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class cXMLHeader {
    
    private cXMLHeaderFrom fromField;
    
    private cXMLHeaderTO toField;
    
    private cXMLHeaderSender senderField;
    



    /// <remarks/>
    public cXMLHeaderFrom From {
        get {
            return this.fromField;
        }
        set {
            this.fromField = value;
        }
    }
    
    /// <remarks/>
    public cXMLHeaderTO To {
        get {
            return this.toField;
        }
        set {
            this.toField = value;
        }
    }
    
    /// <remarks/>
    public cXMLHeaderSender Sender {
        get {
            return this.senderField;
        }
        set {
            this.senderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class cXMLHeaderFrom {
    
    private cXMLHeaderFromCredential credentialField;
    
    /// <remarks/>
    public cXMLHeaderFromCredential Credential {
        get {
            return this.credentialField;
        }
        set {
            this.credentialField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class cXMLHeaderFromCredential {
    
    private string identityField;
    
    private string domainField;
    
    /// <remarks/>
    public string Identity {
        get {
            return this.identityField;
        }
        set {
            this.identityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string domain {
        get {
            return this.domainField;
        }
        set {
            this.domainField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class cXMLHeaderTO {
    
    private cXMLHeaderTOCredential credentialField;
    
    /// <remarks/>
    public cXMLHeaderTOCredential Credential {
        get {
            return this.credentialField;
        }
        set {
            this.credentialField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class cXMLHeaderTOCredential {
    
    private string identityField;
    
    private string domainField;
    
    /// <remarks/>
    public string Identity {
        get {
            return this.identityField;
        }
        set {
            this.identityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string domain {
        get {
            return this.domainField;
        }
        set {
            this.domainField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class cXMLHeaderSender {
    
    private cXMLHeaderSenderCredential credentialField;
    
    private string userAgentField;
    
    /// <remarks/>
    public cXMLHeaderSenderCredential Credential {
        get {
            return this.credentialField;
        }
        set {
            this.credentialField = value;
        }
    }
    
    /// <remarks/>
    public string UserAgent {
        get {
            return this.userAgentField;
        }
        set {
            this.userAgentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class cXMLHeaderSenderCredential {
    
    private string identityField;
    
    private string sharedSecretField;
    
    private string domainField;
    
    /// <remarks/>
    public string Identity {
        get {
            return this.identityField;
        }
        set {
            this.identityField = value;
        }
    }
    
    /// <remarks/>
    public string SharedSecret {
        get {
            return this.sharedSecretField;
        }
        set {
            this.sharedSecretField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string domain {
        get {
            return this.domainField;
        }
        set {
            this.domainField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class cXMLRequest {
    
    private cXMLRequestPunchOutSetupRequest punchOutSetupRequestField;
    
    private string deploymentModeField;
    
    /// <remarks/>
    public cXMLRequestPunchOutSetupRequest PunchOutSetupRequest {
        get {
            return this.punchOutSetupRequestField;
        }
        set {
            this.punchOutSetupRequestField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string deploymentMode {
        get {
            return this.deploymentModeField;
        }
        set {
            this.deploymentModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class cXMLRequestPunchOutSetupRequest {
    
    private string buyerCookieField;
    
    private cXMLRequestPunchOutSetupRequestExtrinsic[] extrinsicField;
    
    private cXMLRequestPunchOutSetupRequestBrowserFormPost browserFormPostField;
    
    private cXMLRequestPunchOutSetupRequestSupplierSetup supplierSetupField;
    
    private cXMLRequestPunchOutSetupRequestShipTo shipToField;
    
    private string operationField;
    
    /// <remarks/>
    public string BuyerCookie {
        get {
            return this.buyerCookieField;
        }
        set {
            this.buyerCookieField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Extrinsic")]
    public cXMLRequestPunchOutSetupRequestExtrinsic[] Extrinsic {
        get {
            return this.extrinsicField;
        }
        set {
            this.extrinsicField = value;
        }
    }

    
    /// <remarks/>
    public cXMLRequestPunchOutSetupRequestBrowserFormPost BrowserFormPost {
        get {
            return this.browserFormPostField;
        }
        set {
            this.browserFormPostField = value;
        }
    }
    
    /// <remarks/>
    public cXMLRequestPunchOutSetupRequestSupplierSetup SupplierSetup {
        get {
            return this.supplierSetupField;
        }
        set {
            this.supplierSetupField = value;
        }
    }
    
    /// <remarks/>
    public cXMLRequestPunchOutSetupRequestShipTo ShipTo {
        get {
            return this.shipToField;
        }
        set {
            this.shipToField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string operation {
        get {
            return this.operationField;
        }
        set {
            this.operationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class cXMLRequestPunchOutSetupRequestExtrinsic {
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }


}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class cXMLRequestPunchOutSetupRequestBrowserFormPost {
    
    private string uRLField;
    
    /// <remarks/>
    public string URL {
        get {
            return this.uRLField;
        }
        set {
            this.uRLField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class cXMLRequestPunchOutSetupRequestSupplierSetup {
    
    private string uRLField;
    
    /// <remarks/>
    public string URL {
        get {
            return this.uRLField;
        }
        set {
            this.uRLField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class cXMLRequestPunchOutSetupRequestShipTo {
    
    private cXMLRequestPunchOutSetupRequestShipToAddress addressField;
    
    /// <remarks/>
    public cXMLRequestPunchOutSetupRequestShipToAddress Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class cXMLRequestPunchOutSetupRequestShipToAddress {
    
    private cXMLRequestPunchOutSetupRequestShipToAddressName nameField;
    
    private cXMLRequestPunchOutSetupRequestShipToAddressPostalAddress postalAddressField;
    
    private string addressIDField;
    
    /// <remarks/>
    public cXMLRequestPunchOutSetupRequestShipToAddressName Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public cXMLRequestPunchOutSetupRequestShipToAddressPostalAddress PostalAddress {
        get {
            return this.postalAddressField;
        }
        set {
            this.postalAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string addressID {
        get {
            return this.addressIDField;
        }
        set {
            this.addressIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class cXMLRequestPunchOutSetupRequestShipToAddressName {
    
    private string langField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class cXMLRequestPunchOutSetupRequestShipToAddressPostalAddress {
    
    private string streetField;
    
    private string cityField;
    
    private string stateField;
    
    private ushort postalCodeField;
    
    private cXMLRequestPunchOutSetupRequestShipToAddressPostalAddressCountry countryField;
    
    /// <remarks/>
    public string Street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public string State {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    public ushort PostalCode {
        get {
            return this.postalCodeField;
        }
        set {
            this.postalCodeField = value;
        }
    }
    
    /// <remarks/>
    public cXMLRequestPunchOutSetupRequestShipToAddressPostalAddressCountry Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class cXMLRequestPunchOutSetupRequestShipToAddressPostalAddressCountry
{

    private string isoCountryCodeField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string isoCountryCode
    {
        get
        {
            return this.isoCountryCodeField;
        }
        set
        {
            this.isoCountryCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class cXMLResponse
    {

        private cXMLResponseStatus statusField;

        private cXMLResponsePunchOutSetupResponse punchOutSetupResponseField;

        /// <remarks/>
        public cXMLResponseStatus Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        public cXMLResponsePunchOutSetupResponse PunchOutSetupResponse
        {
            get
            {
                return this.punchOutSetupResponseField;
            }
            set
            {
                this.punchOutSetupResponseField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class cXMLResponseStatus
    {

        private string codeField;

        private string textField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class cXMLResponsePunchOutSetupResponse
    {

        private cXMLResponsePunchOutSetupResponseStartPage startPageField;

        /// <remarks/>
        public cXMLResponsePunchOutSetupResponseStartPage StartPage
        {
            get
            {
                return this.startPageField;
            }
            set
            {
                this.startPageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class cXMLResponsePunchOutSetupResponseStartPage
    {

        private string uRLField;

        /// <remarks/>
        public string URL
        {
            get
            {
                return this.uRLField;
            }
            set
            {
                this.uRLField = value;
            }
        }

        //    public Root()
        //{
        //}

        //public Root(cXMLException Ex)
        //{
        //    Init();
        //    m_Response = new Response(Ex);
        //}

        //public Root(cXMLType Type, IC_iProcurement myIC_iProcurement)
        //{
        //    Init();

        //    switch(Type)
        //    {
        //        case cXMLType.SetupResponse:
        //            m_Response = new Response(myIC_iProcurement);
        //            break;

        //        //case cXMLType.OrderMessage:
        //        //    m_Header = new Header(myIC_iProcurement);
        //        //    m_Message = new Message(myIC_iProcurement);
        //        //    break;
        //    }
        //}

        //private void Init()
        //{
        //    m_PayloadID = string.Format("{0}@btol.com", DateTime.Now.ToString("yyyyMMddHHmmssfffffff"));
        //    m_Language = "en-US";
        //    m_TimeStamp = GetDateTimeString();
        //}
    }

//}