//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT.TS360API.WebAPI.ServiceReferencePunchOut {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateUserResult", Namespace="http://schemas.datacontract.org/2004/07/BTNextGen.Commerce.Portal.UI.Profiles.Aja" +
        "xServices.Contracts")]
    [System.SerializableAttribute()]
    public partial class CreateUserResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="BTNextGen", ConfigurationName="ServiceReferencePunchOut.PunchOutService")]
    public interface PunchOutService {
        
        [System.ServiceModel.OperationContractAttribute(Action="BTNextGen/PunchOutService/CreateNewUser", ReplyAction="BTNextGen/PunchOutService/CreateNewUserResponse")]
        BT.TS360API.WebAPI.ServiceReferencePunchOut.CreateUserResult CreateNewUser(string userEmail, string password, string orgId);
        
        [System.ServiceModel.OperationContractAttribute(Action="BTNextGen/PunchOutService/CreateNewUser", ReplyAction="BTNextGen/PunchOutService/CreateNewUserResponse")]
        System.Threading.Tasks.Task<BT.TS360API.WebAPI.ServiceReferencePunchOut.CreateUserResult> CreateNewUserAsync(string userEmail, string password, string orgId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PunchOutServiceChannel : BT.TS360API.WebAPI.ServiceReferencePunchOut.PunchOutService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PunchOutServiceClient : System.ServiceModel.ClientBase<BT.TS360API.WebAPI.ServiceReferencePunchOut.PunchOutService>, BT.TS360API.WebAPI.ServiceReferencePunchOut.PunchOutService {
        
        public PunchOutServiceClient() {
        }
        
        public PunchOutServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PunchOutServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PunchOutServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PunchOutServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BT.TS360API.WebAPI.ServiceReferencePunchOut.CreateUserResult CreateNewUser(string userEmail, string password, string orgId) {
            return base.Channel.CreateNewUser(userEmail, password, orgId);
        }
        
        public System.Threading.Tasks.Task<BT.TS360API.WebAPI.ServiceReferencePunchOut.CreateUserResult> CreateNewUserAsync(string userEmail, string password, string orgId) {
            return base.Channel.CreateNewUserAsync(userEmail, password, orgId);
        }
    }
}
