//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT.TS360API.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CartResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CartResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BT.TS360API.Common.Resources.CartResource", typeof(CartResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Duplicates.
        /// </summary>
        public static string ApplyDuplicates {
            get {
                return ResourceManager.GetString("ApplyDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basket state is Ordered or Submitted..
        /// </summary>
        public static string BasketStateIsOrderedOrSubmitted {
            get {
                return ResourceManager.GetString("BasketStateIsOrderedOrSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder is not existing.
        /// </summary>
        public static string BTCart_Folder_Not_Exist {
            get {
                return ResourceManager.GetString("BTCart_Folder_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while accessing the folder containing your MARC file.  Please try again.  If the problem occurs again, please contact Technical Support..
        /// </summary>
        public static string BUILD_DIRECTORY {
            get {
                return ResourceManager.GetString("BUILD_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while building your HTML file. Please try again.  If the problem occurs again, please contact Technical Support..
        /// </summary>
        public static string BUILD_EMAIL_HTML {
            get {
                return ResourceManager.GetString("BUILD_EMAIL_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while building a Leader for the MARC file.  Please try again.  If the problem occurs again, please contact Technical Support..
        /// </summary>
        public static string BUILD_LEADER {
            get {
                return ResourceManager.GetString("BUILD_LEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while building your MARC file. 001 tag is a required MARC tag and cannot be deleted..
        /// </summary>
        public static string BUILD_MARC_1001 {
            get {
                return ResourceManager.GetString("BUILD_MARC_1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while building your MARC file. Please try again.  If the problem occurs again, please contact Technical Support..
        /// </summary>
        public static string BUILD_MARC_FILE {
            get {
                return ResourceManager.GetString("BUILD_MARC_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This cart cannot be deleted because it is in a Submitted state. Please contact our Technical Support team if you have any questions..
        /// </summary>
        public static string Cart_Cannot_Deleted {
            get {
                return ResourceManager.GetString("Cart_Cannot_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Cart that you tried to update might have been changed by another user. Please try to refresh your screen or contact our Technical Support team if you have additional questions..
        /// </summary>
        public static string Cart_Changed_By_Other_User {
            get {
                return ResourceManager.GetString("Cart_Changed_By_Other_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again later. If problem persists please click on Live Chat to report the issue.
        /// </summary>
        public static string Cart_General_SQL_Exception_Error_Message {
            get {
                return ResourceManager.GetString("Cart_General_SQL_Exception_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply default grid to cart successfully..
        /// </summary>
        public static string CartAction_ApplyDefault_Successfully {
            get {
                return ResourceManager.GetString("CartAction_ApplyDefault_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply grid template to cart(s) successfully..
        /// </summary>
        public static string CartAction_ApplyTemplate_Successfully {
            get {
                return ResourceManager.GetString("CartAction_ApplyTemplate_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data has been save successfully !.
        /// </summary>
        public static string CartAction_BeforeSharingCart_Successfully {
            get {
                return ResourceManager.GetString("CartAction_BeforeSharingCart_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Zero Quantity Titles/Grid Lines.
        /// </summary>
        public static string CartAction_DeleteZeroQuantity {
            get {
                return ResourceManager.GetString("CartAction_DeleteZeroQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete zero quantity titles/gridlines successfully..
        /// </summary>
        public static string CartAction_DeleteZeroQuantity_Successfully {
            get {
                return ResourceManager.GetString("CartAction_DeleteZeroQuantity_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical to Digital Conversion.
        /// </summary>
        public static string CartActionConvertPBookToEBook {
            get {
                return ResourceManager.GetString("CartActionConvertPBookToEBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy of Cart(s).
        /// </summary>
        public static string CartActionCreateCopyOfCart {
            get {
                return ResourceManager.GetString("CartActionCreateCopyOfCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Cart.
        /// </summary>
        public static string CartActionDeleteCart {
            get {
                return ResourceManager.GetString("CartActionDeleteCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download/Export Cart.
        /// </summary>
        public static string CartActionDownloadExportCart {
            get {
                return ResourceManager.GetString("CartActionDownloadExportCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Cart.
        /// </summary>
        public static string CartActionEmailCart {
            get {
                return ResourceManager.GetString("CartActionEmailCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESP Submission.
        /// </summary>
        public static string CartActionESPSubmission {
            get {
                return ResourceManager.GetString("CartActionESPSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-Click MARC.
        /// </summary>
        public static string CartActionOneClickMarcDownload {
            get {
                return ResourceManager.GetString("CartActionOneClickMarcDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Cart.
        /// </summary>
        public static string CartActionRenameCart {
            get {
                return ResourceManager.GetString("CartActionRenameCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string CartActionReports {
            get {
                return ResourceManager.GetString("CartActionReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Cart.
        /// </summary>
        public static string CartActionTransferCart {
            get {
                return ResourceManager.GetString("CartActionTransferCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save grid line(s) without active Grid Fields..
        /// </summary>
        public static string CartDetail_NoActiveGridField_ErrorMessage {
            get {
                return ResourceManager.GetString("CartDetail_NoActiveGridField_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cart name must be unique..
        /// </summary>
        public static string CartFolder_CreateCartWithNotUniqueName {
            get {
                return ResourceManager.GetString("CartFolder_CreateCartWithNotUniqueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart folder does not match!.
        /// </summary>
        public static string CARTFOLDERNOTMATCH {
            get {
                return ResourceManager.GetString("CARTFOLDERNOTMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart folder not selected.
        /// </summary>
        public static string CartFolderNotSelected {
            get {
                return ResourceManager.GetString("CartFolderNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Primary.
        /// </summary>
        public static string CartLineAction_makeCartPrimary {
            get {
                return ResourceManager.GetString("CartLineAction_makeCartPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cart &lt;b&gt;{0}&lt;/b&gt; has been submitted for copying and format conversion. You will receive an Alert when the process has been completed..
        /// </summary>
        public static string ConvertPBookToEBook_ConfirmSucceedMessage {
            get {
                return ResourceManager.GetString("ConvertPBookToEBook_ConfirmSucceedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create cart, could not find cart folder.
        /// </summary>
        public static string CreateCartFolderNotFound {
            get {
                return ResourceManager.GetString("CreateCartFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a new cart in Received Folder.
        /// </summary>
        public static string CreateCartReceivedFolder {
            get {
                return ResourceManager.GetString("CreateCartReceivedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a new cart in Shared Folder.
        /// </summary>
        public static string CreateCartSharedFolder {
            get {
                return ResourceManager.GetString("CreateCartSharedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart must be not in Ordered or Submitted state..
        /// </summary>
        public static string ErrorCartInOrderedSubmitted {
            get {
                return ResourceManager.GetString("ErrorCartInOrderedSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The line item that you tried to update no longer exists in this cart. Please try to refresh your screen or contact our Technical Support team if you have additional questions..
        /// </summary>
        public static string Line_Item_No_Longer {
            get {
                return ResourceManager.GetString("Line_Item_No_Longer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The line item that you tried to update might have been changed by another user. Please try to refresh your screen or contact our Technical Support team if you have additional questions..
        /// </summary>
        public static string Line_Item_Tried_Update {
            get {
                return ResourceManager.GetString("Line_Item_Tried_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} line item{1} updated successfully.
        /// </summary>
        public static string LineItemsUpdated {
            get {
                return ResourceManager.GetString("LineItemsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Items to Another Cart.
        /// </summary>
        public static string ManageCart_CopyItemsToOtherCart {
            get {
                return ResourceManager.GetString("ManageCart_CopyItemsToOtherCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when create new cart.
        /// </summary>
        public static string ManageCart_ErrorCreateNewCart {
            get {
                return ResourceManager.GetString("ManageCart_ErrorCreateNewCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not leave the cart name empty.
        /// </summary>
        public static string ManageCart_ErrorEmptyCartname {
            get {
                return ResourceManager.GetString("ManageCart_ErrorEmptyCartname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Items to Another Cart.
        /// </summary>
        public static string ManageCart_MoveItemsToOtherCart {
            get {
                return ResourceManager.GetString("ManageCart_MoveItemsToOtherCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Items from Cart.
        /// </summary>
        public static string ManageCart_RemoveItems {
            get {
                return ResourceManager.GetString("ManageCart_RemoveItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while accessing our MARC database.  Please try again.  If the problem occurs again, please contact Technical Support..
        /// </summary>
        public static string MARC_DB_CONNECT {
            get {
                return ResourceManager.GetString("MARC_DB_CONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no MARC data generated while accessing our MARC database.  Please try again.  If the problem occurs again, please contact Technical Support..
        /// </summary>
        public static string MARC_DB_NODATA {
            get {
                return ResourceManager.GetString("MARC_DB_NODATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while reading from our MARC database.  Please try again.  If the problem occurs again, please contact Technical Support..
        /// </summary>
        public static string MARC_DB_READ {
            get {
                return ResourceManager.GetString("MARC_DB_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while sending email.  Please try again.  If the problem occurs again, please contact Technical Support..
        /// </summary>
        public static string MARC_EMAIL_SEND {
            get {
                return ResourceManager.GetString("MARC_EMAIL_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- None --.
        /// </summary>
        public static string MARCProfilerDownload_NoneOption {
            get {
                return ResourceManager.GetString("MARCProfilerDownload_NoneOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No line item was updated..
        /// </summary>
        public static string NoLineItemsUpdated {
            get {
                return ResourceManager.GetString("NoLineItemsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity set to {0}.
        /// </summary>
        public static string QuantitySetTo {
            get {
                return ResourceManager.GetString("QuantitySetTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote Cart.
        /// </summary>
        public static string QuoteCartText {
            get {
                return ResourceManager.GetString("QuoteCartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Quantities.
        /// </summary>
        public static string SetQuantities {
            get {
                return ResourceManager.GetString("SetQuantities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request is being processed, an alert will be sent you to once its processed.
        /// </summary>
        public static string SetQuantitiiesLineItemsExceedThreshold {
            get {
                return ResourceManager.GetString("SetQuantitiiesLineItemsExceedThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select user(s).
        /// </summary>
        public static string SharedCartProfileTab_SelectUsers {
            get {
                return ResourceManager.GetString("SharedCartProfileTab_SelectUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Cart By Account Type.
        /// </summary>
        public static string SplitCartByAccountType {
            get {
                return ResourceManager.GetString("SplitCartByAccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Cart By Requisition Type.
        /// </summary>
        public static string SplitCartByRequisitionType {
            get {
                return ResourceManager.GetString("SplitCartByRequisitionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error! Please contact administrator..
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find duplicate grid lines.
        /// </summary>
        public static string ValidateOptions_DuplicateGridLines {
            get {
                return ResourceManager.GetString("ValidateOptions_DuplicateGridLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find free text fields containing blanks.
        /// </summary>
        public static string ValidateOptions_FreeTextFieldsContainsBlank {
            get {
                return ResourceManager.GetString("ValidateOptions_FreeTextFieldsContainsBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find grid fields containing blanks.
        /// </summary>
        public static string ValidateOptions_GridFieldsContainsBlank {
            get {
                return ResourceManager.GetString("ValidateOptions_GridFieldsContainsBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find grid lines with zero quantity.
        /// </summary>
        public static string ValidateOptions_GridLinesWithZeroQty {
            get {
                return ResourceManager.GetString("ValidateOptions_GridLinesWithZeroQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find titles with no grids.
        /// </summary>
        public static string ValidateOptions_TitleWithNoGrid {
            get {
                return ResourceManager.GetString("ValidateOptions_TitleWithNoGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find titles with zero quantity.
        /// </summary>
        public static string ValidateOptions_TitleWithZeroQty {
            get {
                return ResourceManager.GetString("ValidateOptions_TitleWithZeroQty", resourceCulture);
            }
        }
    }
}
