//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT.TS360API.WebAPI.ServiceReferenceListTransferAPI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/BTNextGen.Biztalk.ListTransferCartsAPI", ConfigurationName="ServiceReferenceListTransferAPI.ListTransferAPI")]
    public interface ListTransferAPI {
        
        // CODEGEN: Generating message contract since the operation SendTS3 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="SendTS3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BT.TS360API.WebAPI.ServiceReferenceListTransferAPI.SendTS3Response SendTS3(BT.TS360API.WebAPI.ServiceReferenceListTransferAPI.SendTS3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SendTS3", ReplyAction="*")]
        System.Threading.Tasks.Task<BT.TS360API.WebAPI.ServiceReferenceListTransferAPI.SendTS3Response> SendTS3Async(BT.TS360API.WebAPI.ServiceReferenceListTransferAPI.SendTS3Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BTNextGen.Biztalk.ListTransferCartsAPI.ListTransferParameters")]
    public partial class ListTransferParameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string userPasswordField;
        
        private string userEmailField;
        
        private string userEmailCCField;
        
        private string cartNameField;
        
        private string cartGroupField;
        
        private string cartNoteField;
        
        private ListTransferParametersItems[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string UserPassword {
            get {
                return this.userPasswordField;
            }
            set {
                this.userPasswordField = value;
                this.RaisePropertyChanged("UserPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string UserEmail {
            get {
                return this.userEmailField;
            }
            set {
                this.userEmailField = value;
                this.RaisePropertyChanged("UserEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string UserEmailCC {
            get {
                return this.userEmailCCField;
            }
            set {
                this.userEmailCCField = value;
                this.RaisePropertyChanged("UserEmailCC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string CartName {
            get {
                return this.cartNameField;
            }
            set {
                this.cartNameField = value;
                this.RaisePropertyChanged("CartName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string CartGroup {
            get {
                return this.cartGroupField;
            }
            set {
                this.cartGroupField = value;
                this.RaisePropertyChanged("CartGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string CartNote {
            get {
                return this.cartNoteField;
            }
            set {
                this.cartNoteField = value;
                this.RaisePropertyChanged("CartNote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Items", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public ListTransferParametersItems[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BTNextGen.Biztalk.ListTransferCartsAPI.ListTransferParameters")]
    public partial class ListTransferParametersItems : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string itemIDField;
        
        private string quantityField;
        
        private string purchaseOrderLineTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ItemID {
            get {
                return this.itemIDField;
            }
            set {
                this.itemIDField = value;
                this.RaisePropertyChanged("ItemID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PurchaseOrderLineText {
            get {
                return this.purchaseOrderLineTextField;
            }
            set {
                this.purchaseOrderLineTextField = value;
                this.RaisePropertyChanged("PurchaseOrderLineText");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendTS3Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BTNextGen.Biztalk.ListTransferCartsAPI.ListTransferParameters", Order=0)]
        public BT.TS360API.WebAPI.ServiceReferenceListTransferAPI.ListTransferParameters ListTransferParameters;
        
        public SendTS3Request() {
        }
        
        public SendTS3Request(BT.TS360API.WebAPI.ServiceReferenceListTransferAPI.ListTransferParameters ListTransferParameters) {
            this.ListTransferParameters = ListTransferParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendTS3Response {
        
        public SendTS3Response() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ListTransferAPIChannel : BT.TS360API.WebAPI.ServiceReferenceListTransferAPI.ListTransferAPI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListTransferAPIClient : System.ServiceModel.ClientBase<BT.TS360API.WebAPI.ServiceReferenceListTransferAPI.ListTransferAPI>, BT.TS360API.WebAPI.ServiceReferenceListTransferAPI.ListTransferAPI {
        
        public ListTransferAPIClient() {
        }
        
        public ListTransferAPIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ListTransferAPIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListTransferAPIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListTransferAPIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BT.TS360API.WebAPI.ServiceReferenceListTransferAPI.SendTS3Response BT.TS360API.WebAPI.ServiceReferenceListTransferAPI.ListTransferAPI.SendTS3(BT.TS360API.WebAPI.ServiceReferenceListTransferAPI.SendTS3Request request) {
            return base.Channel.SendTS3(request);
        }
        
        public void SendTS3(BT.TS360API.WebAPI.ServiceReferenceListTransferAPI.ListTransferParameters ListTransferParameters) {
            BT.TS360API.WebAPI.ServiceReferenceListTransferAPI.SendTS3Request inValue = new BT.TS360API.WebAPI.ServiceReferenceListTransferAPI.SendTS3Request();
            inValue.ListTransferParameters = ListTransferParameters;
            BT.TS360API.WebAPI.ServiceReferenceListTransferAPI.SendTS3Response retVal = ((BT.TS360API.WebAPI.ServiceReferenceListTransferAPI.ListTransferAPI)(this)).SendTS3(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BT.TS360API.WebAPI.ServiceReferenceListTransferAPI.SendTS3Response> BT.TS360API.WebAPI.ServiceReferenceListTransferAPI.ListTransferAPI.SendTS3Async(BT.TS360API.WebAPI.ServiceReferenceListTransferAPI.SendTS3Request request) {
            return base.Channel.SendTS3Async(request);
        }
        
        public System.Threading.Tasks.Task<BT.TS360API.WebAPI.ServiceReferenceListTransferAPI.SendTS3Response> SendTS3Async(BT.TS360API.WebAPI.ServiceReferenceListTransferAPI.ListTransferParameters ListTransferParameters) {
            BT.TS360API.WebAPI.ServiceReferenceListTransferAPI.SendTS3Request inValue = new BT.TS360API.WebAPI.ServiceReferenceListTransferAPI.SendTS3Request();
            inValue.ListTransferParameters = ListTransferParameters;
            return ((BT.TS360API.WebAPI.ServiceReferenceListTransferAPI.ListTransferAPI)(this)).SendTS3Async(inValue);
        }
    }
}
