CREATE VIEW [dbo].[bam_FunctionalAckActivity_ActiveInstances] AS SELECT NULL [RecordID]
, [ActivityID]
, [InterchangeActivityID]
, [GroupControlNo]
, [InterchangeControlNo]
, [ReceiverID]
, [SenderID]
, [ReceiverQ]
, [SenderQ]
, [InterchangeDateTime]
, [Direction]
, [AckProcessingStatus]
, [AckStatusCode]
, [DeliveredTSCount]
, [AcceptedTSCount]
, [AckIcn]
, [AckIcnDate]
, [AckIcnTime]
, [ErrorCode1]
, [ErrorCode2]
, [ErrorCode3]
, [ErrorCode4]
, [ErrorCode5]
, [TimeCreated]
, [RowFlags]
, [AgreementName]
, [LastModified]
 FROM [dbo].[bam_FunctionalAckActivity_Active] WITH (NOLOCK) WHERE IsVisible = 1