CREATE VIEW [dbo].[bam_BatchInterchangeActivity_ActiveInstances] AS SELECT NULL [RecordID]
, [ActivityID]
, [InterchangeControlNo]
, [ReceiverPartyName]
, [SenderPartyName]
, [ReceiverID]
, [SenderID]
, [ReceiverQ]
, [SenderQ]
, [InterchangeDateTime]
, [Direction]
, [TimeCreated]
, [RowFlags]
, [BatchCorrelationID]
, [AgreementName]
, [LastModified]
 FROM [dbo].[bam_BatchInterchangeActivity_Active] WITH (NOLOCK) WHERE IsVisible = 1