CREATE VIEW [dbo].[bam_AS2InterchangeActivity_ActiveInstances] AS SELECT NULL [RecordID]
, [ActivityID]
, [InterchangeControlNo]
, [ReceiverID]
, [SenderID]
, [ReceiverQ]
, [SenderQ]
, [InterchangeDateTime]
, [Direction]
, [MessageID]
, [AS2From]
, [AS2To]
, [TimeCreated]
, [RowFlags]
, [AgreementName]
, [LastModified]
 FROM [dbo].[bam_AS2InterchangeActivity_Active] WITH (NOLOCK) WHERE IsVisible = 1