CREATE VIEW [dbo].[bam_BusinessMessageJournal_ActiveInstances] AS SELECT NULL [RecordID]
, [ActivityID]
, [MessageTrackingID]
, [ActionType]
, [ContainerActivityID]
, [ContainerType]
, [BTSInterchangeID]
, [BTSMessageID]
, [BTSServiceInstanceID]
, [BTSHostName]
, [RoutedToPartyName]
, [LinkedMessageTrackingID]
, [TimeCreated]
, [LastModified]
 FROM [dbo].[bam_BusinessMessageJournal_Active] WITH (NOLOCK) WHERE IsVisible = 1