CREATE VIEW [dbo].[bam_InterchangeStatusActivity_ActiveInstances] AS SELECT NULL [RecordID]
, [ActivityID]
, [InterchangeControlNo]
, [ReceiverID]
, [SenderID]
, [ReceiverQ]
, [SenderQ]
, [ReceiverPartyName]
, [SenderPartyName]
, [InterchangeDateTime]
, [Direction]
, [AckStatusCode]
, [GroupCount]
, [EdiMessageType]
, [PortID]
, [IsInterchangeAckExpected]
, [IsFunctionalAckExpected]
, [TimeCreated]
, [RowFlags]
, [AckCorrelationId]
, [TsCorrelationId]
, [AgreementName]
, [LastModified]
 FROM [dbo].[bam_InterchangeStatusActivity_Active] WITH (NOLOCK) WHERE IsVisible = 1