CREATE VIEW [dbo].[bam_AS2MdnActivity_ActiveInstances] AS SELECT NULL [RecordID]
, [ActivityID]
, [AS2PartyRole]
, [AS2From]
, [AS2To]
, [MessageID]
, [MdnDateTime]
, [MdnDispositionType]
, [DispositionModifierExtType]
, [DispositionModifierExtDescription]
, [MdnEncryptionType]
, [MdnSignatureType]
, [MdnPayloadContentKey]
, [MdnWireContentKey]
, [MdnMicValue]
, [TimeCreated]
, [RowFlags]
, [AgreementName]
, [LastModified]
 FROM [dbo].[bam_AS2MdnActivity_Active] WITH (NOLOCK) WHERE IsVisible = 1