CREATE VIEW [dbo].[bam_ERPOrders_ActiveInstances] AS SELECT NULL [RecordID]
, [ActivityID]
, [PONum]
, [TransNum]
, [AccountNum]
, [TargetERP]
, [PORcvd]
, [POSentERP]
, [ERPAckRcv]
, [NGRHeaderUpdate]
, [NGRLineUpdate]
, [CSAckUpdate]
, [LastModified]
 FROM [dbo].[bam_ERPOrders_Active] WITH (NOLOCK) WHERE IsVisible = 1