CREATE VIEW [dbo].[bam_AS2MessageActivity_ActiveInstances] AS SELECT NULL [RecordID]
, [ActivityID]
, [ReceiverPartyName]
, [SenderPartyName]
, [AS2PartyRole]
, [AS2From]
, [AS2To]
, [MessageID]
, [MessageDateTime]
, [BTSInterchangeID]
, [BTSMessageID]
, [MdnProcessingStatus]
, [MessageEncryptionType]
, [IsMdnExpected]
, [MicAlgorithmType]
, [MessageSignatureType]
, [MessagePayloadContentKey]
, [MessageWireContentKey]
, [MessageMicValue]
, [TimeCreated]
, [RowFlags]
, [IsAS2MessageDuplicate]
, [DaysToCheckDuplicate]
, [Filename]
, [TrackingActivityID]
, [AgreementName]
, [LastModified]
 FROM [dbo].[bam_AS2MessageActivity_Active] WITH (NOLOCK) WHERE IsVisible = 1