CREATE VIEW [dbo].[bam_InterchangeAckActivity_ActiveInstances] AS SELECT NULL [RecordID]
, [ActivityID]
, [InterchangeControlNo]
, [ReceiverID]
, [SenderID]
, [ReceiverQ]
, [SenderQ]
, [InterchangeDateTime]
, [Direction]
, [AckProcessingStatus]
, [AckStatusCode]
, [AckIcn]
, [AckIcnDate]
, [AckIcnTime]
, [AckNoteCode1]
, [AckNoteCode2]
, [TimeCreated]
, [RowFlags]
, [AckCorrelationId]
, [AgreementName]
, [LastModified]
 FROM [dbo].[bam_InterchangeAckActivity_Active] WITH (NOLOCK) WHERE IsVisible = 1