CREATE VIEW [dbo].[bam_PaymentERPTxn_ActiveInstances] AS SELECT NULL [RecordID]
, [ActivityID]
, [rcvERPReq]
, [SndTokenReq]
, [GetTokenReq]
, [SendCyber]
, [rcvCyber]
, [ProfileReq]
, [ProfileResp]
, [ERPSent]
, [MerchantRef]
, [TargetERP]
, [email]
, [cardID]
, [Reason]
, [LastModified]
 FROM [dbo].[bam_PaymentERPTxn_Active] WITH (NOLOCK) WHERE IsVisible = 1