'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1008
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=4.0.30319.1.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
Partial Public Class AppData
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Warehouse")>  _
    Public Warehouse() As AppDataWarehouse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("StatusMessage")>  _
    Public StatusMessage() As AppDataStatusMessage
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("AccountIDType")>  _
    Public AccountIDType() As AppDataAccountIDType
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("ItemIDType")>  _
    Public ItemIDType() As AppDataItemIDType
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("EmailRecipient")>  _
    Public EmailRecipient() As AppDataEmailRecipient
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class AppDataWarehouse
    
    '''<remarks/>
    Public Code As String
    
    '''<remarks/>
    Public Description As String
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class AppDataStatusMessage
    
    '''<remarks/>
    Public Code As String
    
    '''<remarks/>
    Public Description As String
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class AppDataAccountIDType
    
    '''<remarks/>
    Public Code As String
    
    '''<remarks/>
    Public Description As String
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class AppDataItemIDType
    
    '''<remarks/>
    Public Code As String
    
    '''<remarks/>
    Public Description As String
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class AppDataEmailRecipient
    
    '''<remarks/>
    Public Name As String
    
    '''<remarks/>
    Public EmailAddress As String
    
    '''<remarks/>
    Public Group As String
End Class
