'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace UserAlertsService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="AlertMessageTemplateIDEnum", [Namespace]:="http://schemas.datacontract.org/2004/07/IUserAlerts")>  _
    Public Enum AlertMessageTemplateIDEnum As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        None = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        BTFirstLookCDMS = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        MarcDownloadSP = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        SlipReport = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        HoldingsFile = 4
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        BTFirstLooksCATS = 5
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        MassQuantUpdate = 6
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        HoldingsDupChkInactive = 7
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        HoldingsDupChkActive = 8
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        QuotationsExpireNotice = 9
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ESPRankComplete = 10
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ESPRankFailLibrary = 11
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ESPRankFailSystem = 12
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        DownloadCartComplete = 13
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        DownloadCartFail = 14
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        QuotationReport = 15
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        SingleLineReport = 16
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        SplitCart = 17
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ApplyDuplicates = 18
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        BatchEntryComplete = 19
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        BatchEntryFail = 20
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        BatchEntryCompleteErrors = 21
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        CopyCart = 22
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        MergeCart = 23
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        MoveCart = 24
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ApplyGridTemplate = 25
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ESPDistWFundComplete = 26
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ESPDistWFundFail = 27
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ESPDistWOFundComplete = 28
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ESPDistWOFundFail = 29
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ESPFundComplete = 30
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ESPFundFail = 31
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CreateUserAlertMessageResponse", [Namespace]:="http://schemas.datacontract.org/2004/07/IUserAlerts"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CreateUserAlertMessageResponse
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErrorMessageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ErrorMessage() As String
            Get
                Return Me.ErrorMessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ErrorMessageField, value) <> true) Then
                    Me.ErrorMessageField = value
                    Me.RaisePropertyChanged("ErrorMessage")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Status() As String
            Get
                Return Me.StatusField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StatusField, value) <> true) Then
                    Me.StatusField = value
                    Me.RaisePropertyChanged("Status")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GetUserAlertMessageTemplateResponse", [Namespace]:="http://schemas.datacontract.org/2004/07/IUserAlerts"),  _
     System.SerializableAttribute()>  _
    Partial Public Class GetUserAlertMessageTemplateResponse
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AlertMessageTemplateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ConfigReferenceValueField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErrorMessageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AlertMessageTemplate() As String
            Get
                Return Me.AlertMessageTemplateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AlertMessageTemplateField, value) <> true) Then
                    Me.AlertMessageTemplateField = value
                    Me.RaisePropertyChanged("AlertMessageTemplate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ConfigReferenceValue() As String
            Get
                Return Me.ConfigReferenceValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ConfigReferenceValueField, value) <> true) Then
                    Me.ConfigReferenceValueField = value
                    Me.RaisePropertyChanged("ConfigReferenceValue")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ErrorMessage() As String
            Get
                Return Me.ErrorMessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ErrorMessageField, value) <> true) Then
                    Me.ErrorMessageField = value
                    Me.RaisePropertyChanged("ErrorMessage")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Status() As String
            Get
                Return Me.StatusField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StatusField, value) <> true) Then
                    Me.StatusField = value
                    Me.RaisePropertyChanged("Status")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="UserAlertsService.IUserAlerts")>  _
    Public Interface IUserAlerts
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IUserAlerts/CreateUserAlertMessage", ReplyAction:="http://tempuri.org/IUserAlerts/CreateUserAlertMessageResponse")>  _
        Function CreateUserAlertMessage(ByVal AlertMessage As String, ByVal UserID As String, ByVal AlertMessageTemplateID As UserAlertsService.AlertMessageTemplateIDEnum, ByVal SourceSystem As String) As UserAlertsService.CreateUserAlertMessageResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IUserAlerts/GetUserAlertMessageTemplate", ReplyAction:="http://tempuri.org/IUserAlerts/GetUserAlertMessageTemplateResponse")>  _
        Function GetUserAlertMessageTemplate(ByVal AlertMessageTemplateID As UserAlertsService.AlertMessageTemplateIDEnum) As UserAlertsService.GetUserAlertMessageTemplateResponse
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IUserAlertsChannel
        Inherits UserAlertsService.IUserAlerts, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class UserAlertsClient
        Inherits System.ServiceModel.ClientBase(Of UserAlertsService.IUserAlerts)
        Implements UserAlertsService.IUserAlerts
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function CreateUserAlertMessage(ByVal AlertMessage As String, ByVal UserID As String, ByVal AlertMessageTemplateID As UserAlertsService.AlertMessageTemplateIDEnum, ByVal SourceSystem As String) As UserAlertsService.CreateUserAlertMessageResponse Implements UserAlertsService.IUserAlerts.CreateUserAlertMessage
            Return MyBase.Channel.CreateUserAlertMessage(AlertMessage, UserID, AlertMessageTemplateID, SourceSystem)
        End Function
        
        Public Function GetUserAlertMessageTemplate(ByVal AlertMessageTemplateID As UserAlertsService.AlertMessageTemplateIDEnum) As UserAlertsService.GetUserAlertMessageTemplateResponse Implements UserAlertsService.IUserAlerts.GetUserAlertMessageTemplate
            Return MyBase.Channel.GetUserAlertMessageTemplate(AlertMessageTemplateID)
        End Function
    End Class
End Namespace
