CREATE TABLE [tpm].[AS2ProtocolSettings] (
    [SettingsId]                              INT             NOT NULL,
    [IgnoreCertificateNameMismatch]           BIT             NOT NULL,
    [HttpExpect100Continue]                   BIT             NOT NULL,
    [KeepHttpConnectionAlive]                 BIT             NOT NULL,
    [UnfoldHttpHeaders]                       BIT             NOT NULL,
    [AckIgnoreCertificateNameMismatch]        BIT             NOT NULL,
    [AckHttpExpect100Continue]                BIT             NOT NULL,
    [AckKeepHttpConnectionAlive]              BIT             NOT NULL,
    [AckUnfoldHttpHeaders]                    BIT             NOT NULL,
    [MessageEncrypted]                        BIT             NOT NULL,
    [MessageSigned]                           BIT             NOT NULL,
    [MessageCompressed]                       BIT             NOT NULL,
    [EncryptionAlgorithm]                     SMALLINT        NOT NULL,
    [CheckDuplicateInterchangeControlNumber]  BIT             NOT NULL,
    [InterchangeDuplicatesValidity]           SMALLINT        NOT NULL,
    [CheckCertificateRevocationListOnSend]    BIT             NOT NULL,
    [CheckCertificateRevocationListOnReceive] BIT             NOT NULL,
    [OverrideMessageProperties]               BIT             NOT NULL,
    [SuspendDuplicateMessage]                 BIT             NOT NULL,
    [ProcessMDNtoMsgBox]                      BIT             NOT NULL,
    [TransmitFileNameInMimeHeader]            BIT             NOT NULL,
    [FileNameTemplate]                        NVARCHAR (2048) NULL,
    [SuspendMessageOnFileNameGenerationError] BIT             NOT NULL,
    [AutogenerateFileName]                    BIT             NULL,
    [MessageContentType]                      NVARCHAR (256)  NOT NULL,
    [NeedMdn]                                 BIT             NOT NULL,
    [NeedSignedMdn]                           BIT             NOT NULL,
    [MdnHashingAlgorithm]                     SMALLINT        NOT NULL,
    [NeedAsynchronousMdn]                     BIT             NOT NULL,
    [ReceiptDeliveryUrl]                      NVARCHAR (256)  NULL,
    [DispositionNotificationTo]               NVARCHAR (256)  NULL,
    [ResendIfMdnNotReceived]                  BIT             NOT NULL,
    [ResendIntervalTicks]                     BIGINT          NOT NULL,
    [MaxResendAttempts]                       INT             NOT NULL,
    [ResendTimeoutTicks]                      BIGINT          NOT NULL,
    [HttpRetryTimeoutTicks]                   BIGINT          NOT NULL,
    [OverrideSendPort]                        BIT             NOT NULL,
    [MinimumHttpRetryTicks]                   BIGINT          NOT NULL,
    [MaximumHttpRetryAttempts]                INT             NOT NULL,
    [SignOutboundMdnIfOptional]               BIT             NOT NULL,
    [MDNText]                                 NVARCHAR (1024) NULL,
    [EnableNRRForInboundEncodedMessages]      BIT             NOT NULL,
    [EnableNRRForInboundDecodedMessages]      BIT             NOT NULL,
    [EnableNRRForOutboundMDN]                 BIT             NOT NULL,
    [EnableNRRForOutboundEncodedMessages]     BIT             NOT NULL,
    [EnableNRRForOutboundDecodedMessages]     BIT             NOT NULL,
    [EnableNRRForInboundMDN]                  BIT             NOT NULL,
    [OverrideGroupSigningCertificate]         BIT             NOT NULL,
    [CertificateName]                         NVARCHAR (MAX)  NULL,
    [CertificateThumbprint]                   NVARCHAR (256)  NULL,
    [version]                                 ROWVERSION      NOT NULL,
    CONSTRAINT [PK_AS2ProtocolSettings] PRIMARY KEY CLUSTERED ([SettingsId] ASC),
    CONSTRAINT [FK_AS2ProtocolSettings_ProtocolSettings] FOREIGN KEY ([SettingsId]) REFERENCES [tpm].[ProtocolSettings] ([ProtocolSettingsId]) ON DELETE CASCADE
);

