CREATE TABLE [tpm].[EDIFACTProtocolSettings] (
    [SettingsId]                                INT              NOT NULL,
    [CreateEmptyXmlTagsForTrailingSeparators]   BIT              NOT NULL,
    [MaskSecurityInfo]                          BIT              NOT NULL,
    [PreserveInterchange]                       BIT              NOT NULL,
    [SuspendInterchangeOnError]                 BIT              NOT NULL,
    [UseDotAsDecimalIndicator]                  BIT              DEFAULT ((1)) NOT NULL,
    [TargetNamespace]                           NVARCHAR (230)   NOT NULL,
    [MessageFilterType]                         SMALLINT         NOT NULL,
    [CharacterSet]                              SMALLINT         NOT NULL,
    [ProtocolVersion]                           SMALLINT         NOT NULL,
    [DataElementSeparator]                      INT              NOT NULL,
    [ComponentSeparator]                        INT              NOT NULL,
    [SegmentTerminator]                         INT              NOT NULL,
    [DecimalPointIndicator]                     SMALLINT         NOT NULL,
    [ReleaseIndicator]                          INT              NOT NULL,
    [RepetitionSeparator]                       INT              NOT NULL,
    [SegmentTerminatorSuffix]                   SMALLINT         NOT NULL,
    [EnforceCharacterSet]                       BIT              NOT NULL,
    [ValidateEDITypes]                          BIT              NOT NULL,
    [ValidateXSDTypes]                          BIT              NOT NULL,
    [AllowLeadingAndTrailingSpacesAndZeroes]    BIT              NOT NULL,
    [TrailingSeparatorPolicy]                   SMALLINT         NOT NULL,
    [CheckDuplicateInterchangeControlNumber]    BIT              NOT NULL,
    [InterchangeDuplicatesValidity]             SMALLINT         NOT NULL,
    [CheckDuplicateGroupControlNumber]          BIT              NOT NULL,
    [CheckDuplicateTransactionSetControlNumber] BIT              NOT NULL,
    [NeedTechnicalAck]                          BIT              NOT NULL,
    [BatchTechnicalAck]                         BIT              NOT NULL,
    [NeedFunctionalAck]                         BIT              NOT NULL,
    [BatchFunctionalAck]                        BIT              NOT NULL,
    [GenerateLoopForValidMessagesInAck]         BIT              NOT NULL,
    [RouteAcktoSendPipeline]                    BIT              NOT NULL,
    [ProcessingPriorityCode]                    NVARCHAR (1)     NULL,
    [CommunicationAgreementId]                  NVARCHAR (40)    NULL,
    [ApplyDelimiterStringAdvice]                BIT              NOT NULL,
    [ApplicationReferenceId]                    NVARCHAR (15)    NULL,
    [InterchangeControlNumberLowerBound]        BIGINT           NOT NULL,
    [InterchangeControlNumberUpperBound]        BIGINT           NOT NULL,
    [InterchangeControlNumberRollover]          BIT              NOT NULL,
    [InterchangeControlNumberPrefix]            NVARCHAR (14)    NULL,
    [InterchangeControlNumberSuffix]            NVARCHAR (14)    NULL,
    [SenderReverseRoutingAddress]               NVARCHAR (15)    NULL,
    [ReceiverReverseRoutingAddress]             NVARCHAR (15)    NULL,
    [SSOIdentifier]                             UNIQUEIDENTIFIER NULL,
    [CreateGroupingSegments]                    BIT              NOT NULL,
    [GroupApplicationSenderId]                  NVARCHAR (35)    NULL,
    [GroupApplicationSenderQualifier]           NVARCHAR (15)    NULL,
    [GroupApplicationReceiverId]                NVARCHAR (35)    NULL,
    [GroupApplicationReceiverQualifier]         NVARCHAR (15)    NULL,
    [EnableDefaultGroupHeaders]                 BIT              NOT NULL,
    [FunctionalGroupId]                         NVARCHAR (6)     NULL,
    [GroupControllingAgencyCode]                NVARCHAR (6)     NULL,
    [GroupMessageVersion]                       NVARCHAR (6)     NULL,
    [GroupMessageRelease]                       NVARCHAR (6)     NULL,
    [GroupAssociationAssignedCode]              NVARCHAR (6)     NULL,
    [GroupControlNumberLowerBound]              BIGINT           NOT NULL,
    [GroupControlNumberUpperBound]              BIGINT           NOT NULL,
    [GroupControlNumberRollover]                BIT              NOT NULL,
    [GroupControlNumberPrefix]                  NVARCHAR (14)    NULL,
    [GroupControlNumberSuffix]                  NVARCHAR (14)    NULL,
    [TSApplyNewId]                              BIT              NOT NULL,
    [TSControlNumberPrefix]                     NVARCHAR (14)    NULL,
    [TSControlNumberSuffix]                     NVARCHAR (14)    NULL,
    [TSControlNumberLowerBound]                 BIGINT           NOT NULL,
    [TSControlNumberUpperBound]                 BIGINT           NOT NULL,
    [TSControlNumberRollover]                   BIT              NOT NULL,
    [AcknowledgementControlNumberPrefix]        NVARCHAR (14)    NULL,
    [AcknowledgementControlNumberSuffix]        NVARCHAR (14)    NULL,
    [AcknowledgementControlNumberLowerBound]    BIGINT           NOT NULL,
    [AcknowledgementControlNumberUpperBound]    BIGINT           NOT NULL,
    [AcknowledgementControlNumberRollover]      BIT              NOT NULL,
    [IsTestInterchange]                         BIT              NOT NULL,
    [version]                                   ROWVERSION       NOT NULL,
    CONSTRAINT [PK_EDIFACTProtocolSettings] PRIMARY KEY CLUSTERED ([SettingsId] ASC),
    CONSTRAINT [FK_EDIFACTProtocolSettings_ProtocolSettings] FOREIGN KEY ([SettingsId]) REFERENCES [tpm].[ProtocolSettings] ([ProtocolSettingsId]) ON DELETE CASCADE
);

