CREATE TABLE [tpm].[X12ProtocolSettings] (
    [SettingsId]                                INT              NOT NULL,
    [SSOIdentifier]                             UNIQUEIDENTIFIER NULL,
    [FilterListType]                            SMALLINT         NOT NULL,
    [CreateEmptyXmlTagsForTrailingSeparators]   BIT              NOT NULL,
    [MaskSecurityInfo]                          BIT              NOT NULL,
    [ConvertImpliedDecimal]                     BIT              NOT NULL,
    [PreserveInterchange]                       BIT              NOT NULL,
    [SuspendInterchangeOnError]                 BIT              NOT NULL,
    [UseDotAsDecimalIndicator]                  BIT              DEFAULT ((1)) NOT NULL,
    [TargetNamespace]                           NVARCHAR (230)   NOT NULL,
    [DataElementSeparator]                      INT              NOT NULL,
    [ComponentSeparator]                        INT              NOT NULL,
    [SegmentTerminator]                         INT              NOT NULL,
    [SegmentTerminatorSuffix]                   SMALLINT         NOT NULL,
    [ReplaceSeparatorsInPayload]                BIT              NULL,
    [ReplaceChar]                               INT              NULL,
    [NeedTechnicalAck]                          BIT              NOT NULL,
    [BatchTechnicalAck]                         BIT              NOT NULL,
    [NeedFunctionalAck]                         BIT              NOT NULL,
    [BatchFunctionalAck]                        BIT              NOT NULL,
    [GenerateLoopForValidMessagesInAck]         BIT              NOT NULL,
    [RouteAcktoSendPipeline]                    BIT              NOT NULL,
    [AcknowledgementControlNumberPrefix]        NVARCHAR (9)     NULL,
    [AcknowledgementControlNumberSuffix]        NVARCHAR (9)     NULL,
    [AcknowledgementControlNumberLowerBound]    INT              NOT NULL,
    [AcknowledgementControlNumberUpperBound]    INT              NOT NULL,
    [AcknowledgementControlNumberRollover]      BIT              NOT NULL,
    [CharacterSet]                              SMALLINT         NOT NULL,
    [ValidateCharacterSet]                      BIT              NOT NULL,
    [ValidateEDITypes]                          BIT              NOT NULL,
    [ValidateExtended]                          BIT              NOT NULL,
    [AllowLeadingAndTrailingSpacesAndZeroes]    BIT              NOT NULL,
    [TrailingSeparatorPolicy]                   SMALLINT         NOT NULL,
    [CheckDuplicateInterchangeControlNumber]    BIT              NOT NULL,
    [InterchangeDuplicatesValidity]             SMALLINT         NOT NULL,
    [CheckDuplicateGroupControlNumber]          BIT              NOT NULL,
    [CheckDuplicateTransactionSetControlNumber] BIT              NOT NULL,
    [ControlStandardsID]                        INT              NOT NULL,
    [UseControlStandardsIDAsRepSep]             BIT              NOT NULL,
    [ControlVersionNumber]                      NVARCHAR (5)     NOT NULL,
    [InterchangeControlNumberLowerBound]        INT              NOT NULL,
    [InterchangeControlNumberUpperBound]        INT              NOT NULL,
    [InterchangeControlNumberRollover]          BIT              NOT NULL,
    [GroupControlNumberLowerBound]              INT              NOT NULL,
    [GroupControlNumberUpperBound]              INT              NOT NULL,
    [GroupControlNumberRollover]                BIT              NOT NULL,
    [EnableDefaultGroupHeaders]                 BIT              NOT NULL,
    [FunctionalGroupId]                         NVARCHAR (15)    NULL,
    [GroupDateFormat]                           SMALLINT         NOT NULL,
    [GroupTimeFormat]                           SMALLINT         NOT NULL,
    [GroupResponsibleAgencyCode]                SMALLINT         NULL,
    [GroupHeaderVersion]                        NVARCHAR (12)    NULL,
    [SenderApplicationId]                       NVARCHAR (15)    NULL,
    [ReceiverApplicationId]                     NVARCHAR (15)    NULL,
    [TSApplyNewId]                              BIT              NOT NULL,
    [TSControlNumberPrefix]                     NVARCHAR (9)     NULL,
    [TSControlNumberSuffix]                     NVARCHAR (9)     NULL,
    [TSControlNumberLowerBound]                 INT              NOT NULL,
    [TSControlNumberUpperBound]                 INT              NOT NULL,
    [TSControlNumberRollover]                   BIT              NOT NULL,
    [UsageIndicator]                            SMALLINT         NOT NULL,
    [version]                                   ROWVERSION       NOT NULL,
    CONSTRAINT [PK_X12ProtocolSettings] PRIMARY KEY CLUSTERED ([SettingsId] ASC),
    CONSTRAINT [FK_X12ProtocolSettings_ProtocolSettings] FOREIGN KEY ([SettingsId]) REFERENCES [tpm].[ProtocolSettings] ([ProtocolSettingsId]) ON DELETE CASCADE
);

