//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT.TS360API.ExternalServices.CSProfileServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService", ConfigurationName="CSProfileServiceReference.ProfilesWebServiceSoap")]
    public interface ProfilesWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/CreateProf" +
            "ile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BT.TS360API.ExternalServices.CSProfileServiceReference.CreateProfileResponse CreateProfile(BT.TS360API.ExternalServices.CSProfileServiceReference.CreateProfileRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/CreateProf" +
            "ile", ReplyAction="*")]
        System.Threading.Tasks.Task<BT.TS360API.ExternalServices.CSProfileServiceReference.CreateProfileResponse> CreateProfileAsync(BT.TS360API.ExternalServices.CSProfileServiceReference.CreateProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/GetProfile" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlElement GetProfile(string primaryKeyValue, string profileType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/GetProfile" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlElement> GetProfileAsync(string primaryKeyValue, string profileType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/GetMultipl" +
            "eProfiles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlElement GetMultipleProfiles(string[] primaryKeyList, string profileType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/GetMultipl" +
            "eProfiles", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlElement> GetMultipleProfilesAsync(string[] primaryKeyList, string profileType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/UpdateProf" +
            "ile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BT.TS360API.ExternalServices.CSProfileServiceReference.UpdateProfileResponse UpdateProfile(BT.TS360API.ExternalServices.CSProfileServiceReference.UpdateProfileRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/UpdateProf" +
            "ile", ReplyAction="*")]
        System.Threading.Tasks.Task<BT.TS360API.ExternalServices.CSProfileServiceReference.UpdateProfileResponse> UpdateProfileAsync(BT.TS360API.ExternalServices.CSProfileServiceReference.UpdateProfileRequest request);
        
        // CODEGEN: Parameter 'DeleteProfileResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/DeleteProf" +
            "ile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BT.TS360API.ExternalServices.CSProfileServiceReference.DeleteProfileResponse DeleteProfile(BT.TS360API.ExternalServices.CSProfileServiceReference.DeleteProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/DeleteProf" +
            "ile", ReplyAction="*")]
        System.Threading.Tasks.Task<BT.TS360API.ExternalServices.CSProfileServiceReference.DeleteProfileResponse> DeleteProfileAsync(BT.TS360API.ExternalServices.CSProfileServiceReference.DeleteProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/GetAllSite" +
            "Terms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlElement GetAllSiteTerms();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/GetAllSite" +
            "Terms", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlElement> GetAllSiteTermsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/GetSiteTer" +
            "m", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlElement GetSiteTerm(string siteTermName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/GetSiteTer" +
            "m", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlElement> GetSiteTermAsync(string siteTermName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/CreateSite" +
            "Term", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void CreateSiteTerm(System.Xml.XmlElement siteTermXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/CreateSite" +
            "Term", ReplyAction="*")]
        System.Threading.Tasks.Task CreateSiteTermAsync(System.Xml.XmlElement siteTermXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/UpdateSite" +
            "Term", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void UpdateSiteTerm(System.Xml.XmlElement siteTermXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/UpdateSite" +
            "Term", ReplyAction="*")]
        System.Threading.Tasks.Task UpdateSiteTermAsync(System.Xml.XmlElement siteTermXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/DeleteSite" +
            "Term", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DeleteSiteTerm(string siteTermName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/DeleteSite" +
            "Term", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteSiteTermAsync(string siteTermName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/GetSearcha" +
            "bleEntities", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetSearchableEntities();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/GetSearcha" +
            "bleEntities", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetSearchableEntitiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/ExecuteSea" +
            "rch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ExecuteSearch(string profileType, System.Xml.XmlElement searchClause, BT.TS360API.ExternalServices.CSProfileServiceReference.SearchOptions searchOptions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/ExecuteSea" +
            "rch", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ExecuteSearchAsync(string profileType, System.Xml.XmlElement searchClause, BT.TS360API.ExternalServices.CSProfileServiceReference.SearchOptions searchOptions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/GetAuthori" +
            "zedTasks", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAuthorizedTasks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/GetAuthori" +
            "zedTasks", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAuthorizedTasksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/GetAuthori" +
            "zedProfileDefinitionNames", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetAuthorizedProfileDefinitionNames(BT.TS360API.ExternalServices.CSProfileServiceReference.ProfilePermissions requiredPermissions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/GetAuthori" +
            "zedProfileDefinitionNames", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> GetAuthorizedProfileDefinitionNamesAsync(BT.TS360API.ExternalServices.CSProfileServiceReference.ProfilePermissions requiredPermissions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/GetProfile" +
            "PresentationInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlElement GetProfilePresentationInfo(string cultureCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/GetProfile" +
            "PresentationInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlElement> GetProfilePresentationInfoAsync(string cultureCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/GetAllProf" +
            "ileDefinitionNames", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetAllProfileDefinitionNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/GetAllProf" +
            "ileDefinitionNames", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> GetAllProfileDefinitionNamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/GetAllProf" +
            "ileDefinitions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlElement GetAllProfileDefinitions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/GetAllProf" +
            "ileDefinitions", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlElement> GetAllProfileDefinitionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/GetProfile" +
            "Definition", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlElement GetProfileDefinition(string profileType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/GetProfile" +
            "Definition", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlElement> GetProfileDefinitionAsync(string profileType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/RefreshPro" +
            "fileInCache", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void RefreshProfileInCache(string primaryKeyValue, string profileType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/RefreshPro" +
            "fileInCache", ReplyAction="*")]
        System.Threading.Tasks.Task RefreshProfileInCacheAsync(string primaryKeyValue, string profileType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/RefreshAll" +
            "ProfilesInCache", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void RefreshAllProfilesInCache();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/RefreshAll" +
            "ProfilesInCache", ReplyAction="*")]
        System.Threading.Tasks.Task RefreshAllProfilesInCacheAsync();
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://schemas.microsoft.com/CommerceServer/2004/02/WebServices) of message GetServiceVersionRequest does not match the default value (http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2004/02/WebServices/GetServiceVersion" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BT.TS360API.ExternalServices.CSProfileServiceReference.GetServiceVersionResponse GetServiceVersion(BT.TS360API.ExternalServices.CSProfileServiceReference.GetServiceVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2004/02/WebServices/GetServiceVersion" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<BT.TS360API.ExternalServices.CSProfileServiceReference.GetServiceVersionResponse> GetServiceVersionAsync(BT.TS360API.ExternalServices.CSProfileServiceReference.GetServiceVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/GetSearchR" +
            "esultsLimit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetSearchResultsLimit();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService/GetSearchR" +
            "esultsLimit", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetSearchResultsLimitAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService")]
    public partial class ProfileOperationResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string profileTypeField;
        
        private string primaryKeyNameField;
        
        private string primaryKeyValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ProfileType {
            get {
                return this.profileTypeField;
            }
            set {
                this.profileTypeField = value;
                this.RaisePropertyChanged("ProfileType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PrimaryKeyName {
            get {
                return this.primaryKeyNameField;
            }
            set {
                this.primaryKeyNameField = value;
                this.RaisePropertyChanged("PrimaryKeyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PrimaryKeyValue {
            get {
                return this.primaryKeyValueField;
            }
            set {
                this.primaryKeyValueField = value;
                this.RaisePropertyChanged("PrimaryKeyValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/CommerceServer/2004/02/WebServices")]
    public partial class WebServiceVersion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int majorVersionField;
        
        private int minorVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int MajorVersion {
            get {
                return this.majorVersionField;
            }
            set {
                this.majorVersionField = value;
                this.RaisePropertyChanged("MajorVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int MinorVersion {
            get {
                return this.minorVersionField;
            }
            set {
                this.minorVersionField = value;
                this.RaisePropertyChanged("MinorVersion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService")]
    public partial class SearchOptions : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int numberOfRecordsToReturnField;
        
        private int startRecordField;
        
        private string sortPropertiesField;
        
        private bool sortDescendingField;
        
        private string propertiesToReturnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int NumberOfRecordsToReturn {
            get {
                return this.numberOfRecordsToReturnField;
            }
            set {
                this.numberOfRecordsToReturnField = value;
                this.RaisePropertyChanged("NumberOfRecordsToReturn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int StartRecord {
            get {
                return this.startRecordField;
            }
            set {
                this.startRecordField = value;
                this.RaisePropertyChanged("StartRecord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SortProperties {
            get {
                return this.sortPropertiesField;
            }
            set {
                this.sortPropertiesField = value;
                this.RaisePropertyChanged("SortProperties");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool SortDescending {
            get {
                return this.sortDescendingField;
            }
            set {
                this.sortDescendingField = value;
                this.RaisePropertyChanged("SortDescending");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PropertiesToReturn {
            get {
                return this.propertiesToReturnField;
            }
            set {
                this.propertiesToReturnField = value;
                this.RaisePropertyChanged("PropertiesToReturn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateProfile", WrapperNamespace="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService", IsWrapped=true)]
    public partial class CreateProfileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService", Order=0)]
        public System.Xml.XmlElement profileXml;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService", Order=1)]
        public bool inAdapterContext;
        
        public CreateProfileRequest() {
        }
        
        public CreateProfileRequest(System.Xml.XmlElement profileXml, bool inAdapterContext) {
            this.profileXml = profileXml;
            this.inAdapterContext = inAdapterContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateProfileResponse", WrapperNamespace="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService", IsWrapped=true)]
    public partial class CreateProfileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BT.TS360API.ExternalServices.CSProfileServiceReference.ProfileOperationResponse CreateProfileResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService", Order=1)]
        public System.Xml.XmlElement profileXml;
        
        public CreateProfileResponse() {
        }
        
        public CreateProfileResponse(BT.TS360API.ExternalServices.CSProfileServiceReference.ProfileOperationResponse CreateProfileResult, System.Xml.XmlElement profileXml) {
            this.CreateProfileResult = CreateProfileResult;
            this.profileXml = profileXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateProfile", WrapperNamespace="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService", IsWrapped=true)]
    public partial class UpdateProfileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService", Order=0)]
        public System.Xml.XmlElement profileXml;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService", Order=1)]
        public bool forceOverwrite;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService", Order=2)]
        public bool inAdapterContext;
        
        public UpdateProfileRequest() {
        }
        
        public UpdateProfileRequest(System.Xml.XmlElement profileXml, bool forceOverwrite, bool inAdapterContext) {
            this.profileXml = profileXml;
            this.forceOverwrite = forceOverwrite;
            this.inAdapterContext = inAdapterContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateProfileResponse", WrapperNamespace="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService", IsWrapped=true)]
    public partial class UpdateProfileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BT.TS360API.ExternalServices.CSProfileServiceReference.ProfileOperationResponse UpdateProfileResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService", Order=1)]
        public System.Xml.XmlElement profileXml;
        
        public UpdateProfileResponse() {
        }
        
        public UpdateProfileResponse(BT.TS360API.ExternalServices.CSProfileServiceReference.ProfileOperationResponse UpdateProfileResult, System.Xml.XmlElement profileXml) {
            this.UpdateProfileResult = UpdateProfileResult;
            this.profileXml = profileXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteProfile", WrapperNamespace="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService", IsWrapped=true)]
    public partial class DeleteProfileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService", Order=0)]
        public string primaryKeyValue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService", Order=1)]
        public string profileType;
        
        public DeleteProfileRequest() {
        }
        
        public DeleteProfileRequest(string primaryKeyValue, string profileType) {
            this.primaryKeyValue = primaryKeyValue;
            this.profileType = profileType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteProfileResponse", WrapperNamespace="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService", IsWrapped=true)]
    public partial class DeleteProfileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BT.TS360API.ExternalServices.CSProfileServiceReference.ProfileOperationResponse DeleteProfileResult;
        
        public DeleteProfileResponse() {
        }
        
        public DeleteProfileResponse(BT.TS360API.ExternalServices.CSProfileServiceReference.ProfileOperationResponse DeleteProfileResult) {
            this.DeleteProfileResult = DeleteProfileResult;
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/CommerceServer/2006/03/ProfilesWebService")]
    public enum ProfilePermissions {
        
        /// <remarks/>
        None = 1,
        
        /// <remarks/>
        Create = 2,
        
        /// <remarks/>
        Retrieve = 4,
        
        /// <remarks/>
        Update = 8,
        
        /// <remarks/>
        Delete = 16,
        
        /// <remarks/>
        ReadWrite = 32,
        
        /// <remarks/>
        AllAccess = 64,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetServiceVersion", WrapperNamespace="http://schemas.microsoft.com/CommerceServer/2004/02/WebServices", IsWrapped=true)]
    public partial class GetServiceVersionRequest {
        
        public GetServiceVersionRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetServiceVersionResponse", WrapperNamespace="http://schemas.microsoft.com/CommerceServer/2004/02/WebServices", IsWrapped=true)]
    public partial class GetServiceVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/CommerceServer/2004/02/WebServices", Order=0)]
        public BT.TS360API.ExternalServices.CSProfileServiceReference.WebServiceVersion GetServiceVersionResult;
        
        public GetServiceVersionResponse() {
        }
        
        public GetServiceVersionResponse(BT.TS360API.ExternalServices.CSProfileServiceReference.WebServiceVersion GetServiceVersionResult) {
            this.GetServiceVersionResult = GetServiceVersionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProfilesWebServiceSoapChannel : BT.TS360API.ExternalServices.CSProfileServiceReference.ProfilesWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProfilesWebServiceSoapClient : System.ServiceModel.ClientBase<BT.TS360API.ExternalServices.CSProfileServiceReference.ProfilesWebServiceSoap>, BT.TS360API.ExternalServices.CSProfileServiceReference.ProfilesWebServiceSoap {
        
        public ProfilesWebServiceSoapClient() {
        }
        
        public ProfilesWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProfilesWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfilesWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfilesWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BT.TS360API.ExternalServices.CSProfileServiceReference.CreateProfileResponse BT.TS360API.ExternalServices.CSProfileServiceReference.ProfilesWebServiceSoap.CreateProfile(BT.TS360API.ExternalServices.CSProfileServiceReference.CreateProfileRequest request) {
            return base.Channel.CreateProfile(request);
        }
        
        public BT.TS360API.ExternalServices.CSProfileServiceReference.ProfileOperationResponse CreateProfile(ref System.Xml.XmlElement profileXml, bool inAdapterContext) {
            BT.TS360API.ExternalServices.CSProfileServiceReference.CreateProfileRequest inValue = new BT.TS360API.ExternalServices.CSProfileServiceReference.CreateProfileRequest();
            inValue.profileXml = profileXml;
            inValue.inAdapterContext = inAdapterContext;
            BT.TS360API.ExternalServices.CSProfileServiceReference.CreateProfileResponse retVal = ((BT.TS360API.ExternalServices.CSProfileServiceReference.ProfilesWebServiceSoap)(this)).CreateProfile(inValue);
            profileXml = retVal.profileXml;
            return retVal.CreateProfileResult;
        }
        
        public System.Threading.Tasks.Task<BT.TS360API.ExternalServices.CSProfileServiceReference.CreateProfileResponse> CreateProfileAsync(BT.TS360API.ExternalServices.CSProfileServiceReference.CreateProfileRequest request) {
            return base.Channel.CreateProfileAsync(request);
        }
        
        public System.Xml.XmlElement GetProfile(string primaryKeyValue, string profileType) {
            return base.Channel.GetProfile(primaryKeyValue, profileType);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlElement> GetProfileAsync(string primaryKeyValue, string profileType) {
            return base.Channel.GetProfileAsync(primaryKeyValue, profileType);
        }
        
        public System.Xml.XmlElement GetMultipleProfiles(string[] primaryKeyList, string profileType) {
            return base.Channel.GetMultipleProfiles(primaryKeyList, profileType);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlElement> GetMultipleProfilesAsync(string[] primaryKeyList, string profileType) {
            return base.Channel.GetMultipleProfilesAsync(primaryKeyList, profileType);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BT.TS360API.ExternalServices.CSProfileServiceReference.UpdateProfileResponse BT.TS360API.ExternalServices.CSProfileServiceReference.ProfilesWebServiceSoap.UpdateProfile(BT.TS360API.ExternalServices.CSProfileServiceReference.UpdateProfileRequest request) {
            return base.Channel.UpdateProfile(request);
        }
        
        public BT.TS360API.ExternalServices.CSProfileServiceReference.ProfileOperationResponse UpdateProfile(ref System.Xml.XmlElement profileXml, bool forceOverwrite, bool inAdapterContext) {
            BT.TS360API.ExternalServices.CSProfileServiceReference.UpdateProfileRequest inValue = new BT.TS360API.ExternalServices.CSProfileServiceReference.UpdateProfileRequest();
            inValue.profileXml = profileXml;
            inValue.forceOverwrite = forceOverwrite;
            inValue.inAdapterContext = inAdapterContext;
            BT.TS360API.ExternalServices.CSProfileServiceReference.UpdateProfileResponse retVal = ((BT.TS360API.ExternalServices.CSProfileServiceReference.ProfilesWebServiceSoap)(this)).UpdateProfile(inValue);
            profileXml = retVal.profileXml;
            return retVal.UpdateProfileResult;
        }
        
        public System.Threading.Tasks.Task<BT.TS360API.ExternalServices.CSProfileServiceReference.UpdateProfileResponse> UpdateProfileAsync(BT.TS360API.ExternalServices.CSProfileServiceReference.UpdateProfileRequest request) {
            return base.Channel.UpdateProfileAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BT.TS360API.ExternalServices.CSProfileServiceReference.DeleteProfileResponse BT.TS360API.ExternalServices.CSProfileServiceReference.ProfilesWebServiceSoap.DeleteProfile(BT.TS360API.ExternalServices.CSProfileServiceReference.DeleteProfileRequest request) {
            return base.Channel.DeleteProfile(request);
        }
        
        public BT.TS360API.ExternalServices.CSProfileServiceReference.ProfileOperationResponse DeleteProfile(string primaryKeyValue, string profileType) {
            BT.TS360API.ExternalServices.CSProfileServiceReference.DeleteProfileRequest inValue = new BT.TS360API.ExternalServices.CSProfileServiceReference.DeleteProfileRequest();
            inValue.primaryKeyValue = primaryKeyValue;
            inValue.profileType = profileType;
            BT.TS360API.ExternalServices.CSProfileServiceReference.DeleteProfileResponse retVal = ((BT.TS360API.ExternalServices.CSProfileServiceReference.ProfilesWebServiceSoap)(this)).DeleteProfile(inValue);
            return retVal.DeleteProfileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BT.TS360API.ExternalServices.CSProfileServiceReference.DeleteProfileResponse> BT.TS360API.ExternalServices.CSProfileServiceReference.ProfilesWebServiceSoap.DeleteProfileAsync(BT.TS360API.ExternalServices.CSProfileServiceReference.DeleteProfileRequest request) {
            return base.Channel.DeleteProfileAsync(request);
        }
        
        public System.Threading.Tasks.Task<BT.TS360API.ExternalServices.CSProfileServiceReference.DeleteProfileResponse> DeleteProfileAsync(string primaryKeyValue, string profileType) {
            BT.TS360API.ExternalServices.CSProfileServiceReference.DeleteProfileRequest inValue = new BT.TS360API.ExternalServices.CSProfileServiceReference.DeleteProfileRequest();
            inValue.primaryKeyValue = primaryKeyValue;
            inValue.profileType = profileType;
            return ((BT.TS360API.ExternalServices.CSProfileServiceReference.ProfilesWebServiceSoap)(this)).DeleteProfileAsync(inValue);
        }
        
        public System.Xml.XmlElement GetAllSiteTerms() {
            return base.Channel.GetAllSiteTerms();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlElement> GetAllSiteTermsAsync() {
            return base.Channel.GetAllSiteTermsAsync();
        }
        
        public System.Xml.XmlElement GetSiteTerm(string siteTermName) {
            return base.Channel.GetSiteTerm(siteTermName);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlElement> GetSiteTermAsync(string siteTermName) {
            return base.Channel.GetSiteTermAsync(siteTermName);
        }
        
        public void CreateSiteTerm(System.Xml.XmlElement siteTermXml) {
            base.Channel.CreateSiteTerm(siteTermXml);
        }
        
        public System.Threading.Tasks.Task CreateSiteTermAsync(System.Xml.XmlElement siteTermXml) {
            return base.Channel.CreateSiteTermAsync(siteTermXml);
        }
        
        public void UpdateSiteTerm(System.Xml.XmlElement siteTermXml) {
            base.Channel.UpdateSiteTerm(siteTermXml);
        }
        
        public System.Threading.Tasks.Task UpdateSiteTermAsync(System.Xml.XmlElement siteTermXml) {
            return base.Channel.UpdateSiteTermAsync(siteTermXml);
        }
        
        public void DeleteSiteTerm(string siteTermName) {
            base.Channel.DeleteSiteTerm(siteTermName);
        }
        
        public System.Threading.Tasks.Task DeleteSiteTermAsync(string siteTermName) {
            return base.Channel.DeleteSiteTermAsync(siteTermName);
        }
        
        public System.Data.DataSet GetSearchableEntities() {
            return base.Channel.GetSearchableEntities();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetSearchableEntitiesAsync() {
            return base.Channel.GetSearchableEntitiesAsync();
        }
        
        public System.Data.DataSet ExecuteSearch(string profileType, System.Xml.XmlElement searchClause, BT.TS360API.ExternalServices.CSProfileServiceReference.SearchOptions searchOptions) {
            return base.Channel.ExecuteSearch(profileType, searchClause, searchOptions);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ExecuteSearchAsync(string profileType, System.Xml.XmlElement searchClause, BT.TS360API.ExternalServices.CSProfileServiceReference.SearchOptions searchOptions) {
            return base.Channel.ExecuteSearchAsync(profileType, searchClause, searchOptions);
        }
        
        public System.Data.DataSet GetAuthorizedTasks() {
            return base.Channel.GetAuthorizedTasks();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAuthorizedTasksAsync() {
            return base.Channel.GetAuthorizedTasksAsync();
        }
        
        public string[] GetAuthorizedProfileDefinitionNames(BT.TS360API.ExternalServices.CSProfileServiceReference.ProfilePermissions requiredPermissions) {
            return base.Channel.GetAuthorizedProfileDefinitionNames(requiredPermissions);
        }
        
        public System.Threading.Tasks.Task<string[]> GetAuthorizedProfileDefinitionNamesAsync(BT.TS360API.ExternalServices.CSProfileServiceReference.ProfilePermissions requiredPermissions) {
            return base.Channel.GetAuthorizedProfileDefinitionNamesAsync(requiredPermissions);
        }
        
        public System.Xml.XmlElement GetProfilePresentationInfo(string cultureCode) {
            return base.Channel.GetProfilePresentationInfo(cultureCode);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlElement> GetProfilePresentationInfoAsync(string cultureCode) {
            return base.Channel.GetProfilePresentationInfoAsync(cultureCode);
        }
        
        public string[] GetAllProfileDefinitionNames() {
            return base.Channel.GetAllProfileDefinitionNames();
        }
        
        public System.Threading.Tasks.Task<string[]> GetAllProfileDefinitionNamesAsync() {
            return base.Channel.GetAllProfileDefinitionNamesAsync();
        }
        
        public System.Xml.XmlElement GetAllProfileDefinitions() {
            return base.Channel.GetAllProfileDefinitions();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlElement> GetAllProfileDefinitionsAsync() {
            return base.Channel.GetAllProfileDefinitionsAsync();
        }
        
        public System.Xml.XmlElement GetProfileDefinition(string profileType) {
            return base.Channel.GetProfileDefinition(profileType);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlElement> GetProfileDefinitionAsync(string profileType) {
            return base.Channel.GetProfileDefinitionAsync(profileType);
        }
        
        public void RefreshProfileInCache(string primaryKeyValue, string profileType) {
            base.Channel.RefreshProfileInCache(primaryKeyValue, profileType);
        }
        
        public System.Threading.Tasks.Task RefreshProfileInCacheAsync(string primaryKeyValue, string profileType) {
            return base.Channel.RefreshProfileInCacheAsync(primaryKeyValue, profileType);
        }
        
        public void RefreshAllProfilesInCache() {
            base.Channel.RefreshAllProfilesInCache();
        }
        
        public System.Threading.Tasks.Task RefreshAllProfilesInCacheAsync() {
            return base.Channel.RefreshAllProfilesInCacheAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BT.TS360API.ExternalServices.CSProfileServiceReference.GetServiceVersionResponse BT.TS360API.ExternalServices.CSProfileServiceReference.ProfilesWebServiceSoap.GetServiceVersion(BT.TS360API.ExternalServices.CSProfileServiceReference.GetServiceVersionRequest request) {
            return base.Channel.GetServiceVersion(request);
        }
        
        public BT.TS360API.ExternalServices.CSProfileServiceReference.WebServiceVersion GetServiceVersion() {
            BT.TS360API.ExternalServices.CSProfileServiceReference.GetServiceVersionRequest inValue = new BT.TS360API.ExternalServices.CSProfileServiceReference.GetServiceVersionRequest();
            BT.TS360API.ExternalServices.CSProfileServiceReference.GetServiceVersionResponse retVal = ((BT.TS360API.ExternalServices.CSProfileServiceReference.ProfilesWebServiceSoap)(this)).GetServiceVersion(inValue);
            return retVal.GetServiceVersionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BT.TS360API.ExternalServices.CSProfileServiceReference.GetServiceVersionResponse> BT.TS360API.ExternalServices.CSProfileServiceReference.ProfilesWebServiceSoap.GetServiceVersionAsync(BT.TS360API.ExternalServices.CSProfileServiceReference.GetServiceVersionRequest request) {
            return base.Channel.GetServiceVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<BT.TS360API.ExternalServices.CSProfileServiceReference.GetServiceVersionResponse> GetServiceVersionAsync() {
            BT.TS360API.ExternalServices.CSProfileServiceReference.GetServiceVersionRequest inValue = new BT.TS360API.ExternalServices.CSProfileServiceReference.GetServiceVersionRequest();
            return ((BT.TS360API.ExternalServices.CSProfileServiceReference.ProfilesWebServiceSoap)(this)).GetServiceVersionAsync(inValue);
        }
        
        public int GetSearchResultsLimit() {
            return base.Channel.GetSearchResultsLimit();
        }
        
        public System.Threading.Tasks.Task<int> GetSearchResultsLimitAsync() {
            return base.Channel.GetSearchResultsLimitAsync();
        }
    }
}
