//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARCProfilerService.ServiceReference1.UserAlerts {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlertMessageTemplateIDEnum", Namespace="http://schemas.datacontract.org/2004/07/IUserAlerts")]
    public enum AlertMessageTemplateIDEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BTFirstLookCDMS = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MarcDownloadSP = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SlipReport = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HoldingsFile = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BTFirstLooksCATS = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MassQuantUpdate = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateUserAlertMessageResponse", Namespace="http://schemas.datacontract.org/2004/07/IUserAlerts")]
    [System.SerializableAttribute()]
    public partial class CreateUserAlertMessageResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetUserAlertMessageTemplateResponse", Namespace="http://schemas.datacontract.org/2004/07/IUserAlerts")]
    [System.SerializableAttribute()]
    public partial class GetUserAlertMessageTemplateResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlertMessageTemplateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConfigReferenceValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlertMessageTemplate {
            get {
                return this.AlertMessageTemplateField;
            }
            set {
                if ((object.ReferenceEquals(this.AlertMessageTemplateField, value) != true)) {
                    this.AlertMessageTemplateField = value;
                    this.RaisePropertyChanged("AlertMessageTemplate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConfigReferenceValue {
            get {
                return this.ConfigReferenceValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfigReferenceValueField, value) != true)) {
                    this.ConfigReferenceValueField = value;
                    this.RaisePropertyChanged("ConfigReferenceValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.UserAlerts.IUserAlerts")]
    public interface IUserAlerts {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAlerts/CreateUserAlertMessage", ReplyAction="http://tempuri.org/IUserAlerts/CreateUserAlertMessageResponse")]
        MARCProfilerService.ServiceReference1.UserAlerts.CreateUserAlertMessageResponse CreateUserAlertMessage(string AlertMessage, string UserID, MARCProfilerService.ServiceReference1.UserAlerts.AlertMessageTemplateIDEnum AlertMessageTemplateID, string SourceSystem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAlerts/GetUserAlertMessageTemplate", ReplyAction="http://tempuri.org/IUserAlerts/GetUserAlertMessageTemplateResponse")]
        MARCProfilerService.ServiceReference1.UserAlerts.GetUserAlertMessageTemplateResponse GetUserAlertMessageTemplate(MARCProfilerService.ServiceReference1.UserAlerts.AlertMessageTemplateIDEnum AlertMessageTemplateID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserAlertsChannel : MARCProfilerService.ServiceReference1.UserAlerts.IUserAlerts, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserAlertsClient : System.ServiceModel.ClientBase<MARCProfilerService.ServiceReference1.UserAlerts.IUserAlerts>, MARCProfilerService.ServiceReference1.UserAlerts.IUserAlerts {
        
        public UserAlertsClient() {
        }
        
        public UserAlertsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserAlertsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserAlertsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserAlertsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MARCProfilerService.ServiceReference1.UserAlerts.CreateUserAlertMessageResponse CreateUserAlertMessage(string AlertMessage, string UserID, MARCProfilerService.ServiceReference1.UserAlerts.AlertMessageTemplateIDEnum AlertMessageTemplateID, string SourceSystem) {
            return base.Channel.CreateUserAlertMessage(AlertMessage, UserID, AlertMessageTemplateID, SourceSystem);
        }
        
        public MARCProfilerService.ServiceReference1.UserAlerts.GetUserAlertMessageTemplateResponse GetUserAlertMessageTemplate(MARCProfilerService.ServiceReference1.UserAlerts.AlertMessageTemplateIDEnum AlertMessageTemplateID) {
            return base.Channel.GetUserAlertMessageTemplate(AlertMessageTemplateID);
        }
    }
}
