//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTNextGen.Biztalk.Catalog.CommonUtil.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Catalog : global::System.Configuration.ApplicationSettingsBase {
        
        private static Catalog defaultInstance = ((Catalog)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Catalog())));
        
        public static Catalog Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Entertainment Catalog 1</string>
  <string>Book Catalog 1</string>
  <string>Book Catalog 2</string>
  <string>Book Catalog 3</string>
  <string>Book Catalog 4</string>
  <string>Book Catalog 5</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CatalogName {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CatalogName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>6000000000</string>
  <string>0000000000</string>
  <string>0003000001</string>
  <string>0007000001</string>
  <string>0010000001</string>
  <string>7000000001</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection MinValues {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MinValues"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>7000000000</string>
  <string>0003000000</string>
  <string>0007000000</string>
  <string>0010000000</string>
  <string>5999999999</string>
  <string>9999999999</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection MaxValues {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MaxValues"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Catalog_1_Inventory</string>
  <string>Catalog_2_Inventory</string>
  <string>Catalog_3_Inventory</string>
  <string>Catalog_4_Inventory</string>
  <string>Catalog_5_Inventory</string>
  <string>Catalog_5_Inventory</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection InventoryCat {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["InventoryCat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ArchiveFlag {
            get {
                return ((bool)(this["ArchiveFlag"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int MaxProductRecord {
            get {
                return ((int)(this["MaxProductRecord"]));
            }
        }
    }
}
