CREATE TABLE [dbo].[bam_AS2MessageActivity_Active] (
    [ActivityID]               NVARCHAR (128)  NOT NULL,
    [IsVisible]                BIT             DEFAULT (NULL) NULL,
    [IsComplete]               BIT             DEFAULT (NULL) NULL,
    [ReceiverPartyName]        NVARCHAR (256)  NULL,
    [SenderPartyName]          NVARCHAR (256)  NULL,
    [AS2PartyRole]             INT             NULL,
    [AS2From]                  NVARCHAR (128)  NULL,
    [AS2To]                    NVARCHAR (128)  NULL,
    [MessageID]                NVARCHAR (1000) NULL,
    [MessageDateTime]          DATETIME        NULL,
    [BTSInterchangeID]         NVARCHAR (128)  NULL,
    [BTSMessageID]             NVARCHAR (128)  NULL,
    [MdnProcessingStatus]      INT             NULL,
    [MessageEncryptionType]    INT             NULL,
    [IsMdnExpected]            INT             NULL,
    [MicAlgorithmType]         INT             NULL,
    [MessageSignatureType]     INT             NULL,
    [MessagePayloadContentKey] NVARCHAR (40)   NULL,
    [MessageWireContentKey]    NVARCHAR (40)   NULL,
    [MessageMicValue]          NVARCHAR (50)   NULL,
    [TimeCreated]              DATETIME        NULL,
    [RowFlags]                 INT             NULL,
    [IsAS2MessageDuplicate]    INT             NULL,
    [DaysToCheckDuplicate]     INT             NULL,
    [Filename]                 NVARCHAR (1000) NULL,
    [TrackingActivityID]       NVARCHAR (128)  NULL,
    [AgreementName]            NVARCHAR (256)  NULL,
    [LastModified]             DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([ActivityID] ASC)
);

